### ISSUE TITLE
unknown web session id

### ISSUE THREAD

**Issue by wesleifelix** [pagseguro/pagseguro-modulo-prestashop#103]
Começou hoje aparecer sempre esta informação na tela. Mesmo gerando um novo token. Ele fica sempre devolvendo este status.

**Comment by prestabr** [comment]
Bom Dia wesleifelix,

Qual informação aparece na tela? Tem mais detalhes? Se puder postar um print...

Atenciosamente,
Equipe PrestaBR

**Comment by wesleifelix** [comment]
GEThttps://ws.pagseguro.uol.com.br/payment-methods?callback=callbackPaymentMethods&sessionId=undefined&amount=1.19&Accept=application/vnd.pagseguro.com.br.v1%2Bjson;charset=ISO-8859-1
[HTTP/1.1 202 Accepted 175ms]

{…}
​
10003: "O TOKEN WEB é inválido."
​
<prototype>: Object { … }
v_39_c410851ba6358804c30134ce47f417ff.js:453:343
{…}
​
59001: "unknown web session id"
​

**Comment by wesleifelix** [comment]
Usando o modulo antigo do FK PagSeguro, o token autoriza normalmente.

**Comment by prestabr** [comment]
Olá wesleifelix,

Você já se certificou se o token utilizado é o de produtoção e o ambiente também? O mesmo vale para o ambiente sandbox. Lembrando que este é o módulo Oficial da PagSeguro para Checkout Transparente.

Atenciosamente,
Equipe PrestaBR

**Comment by wesleifelix** [comment]
O modulo oficial sem alterações em modo de produção

**Comment by prestabr** [comment]
Olá wesleifelix,

Infelizmente não conseguimos reproduzir este problema do nosso lado, ter o token funcional na loja virtual é algo muito básico.

Pode ser algo relacionado à sua hospedagem, confere estes tópicos:

https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/96
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/91
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/80 - Solução: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/80#issuecomment-610455265 (talvez seja o mesmo problema que o seu)
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/55

Um problema bastante comum são as permissões erradas nos arquivos e pastas na sua /public_html/modules/pagseguropro/, o ideal é 755 para pastas e 644 para arquivos.

Atenciosamente,
Equipe PrestaBR
