### ISSUE TITLE
Atualização do módulo p/ Prestashop 1.7.6.2

### ISSUE THREAD

**Issue by rafachiarello** [pagseguro/pagseguro-modulo-prestashop#104]
Olá!
Verifiquei que houve upgrade do módulo pagseguro para versão 1.1.0 e gostaria de saber se o procedimento de atualização para esta nova versão é o mesmo da instalação. Tenho instalada a versão 1.0.3.
Att.
Rafael

**Comment by prestabr** [comment]
Boa Noite rafachiarello,

Sim, o procedimento é o mesmo da instalação, pode seguir este passo-a-passo: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#instala%C3%A7%C3%A3o

Após atualizar é sempre bom limpar o cache, no seu backoffice acessa: "Parâmetros Avançados > Desempenho, no canto superior direito no botão "Limpar Cache".

Atenciosamente,
Equipe PrestaBR

**Comment by rafachiarello** [comment]
ok, muito obrigado pelo breve retorno!
