### ISSUE TITLE
App authentication + Split pagamentos

### ISSUE THREAD

**Issue by 3W3R50N** [pagseguro/pagseguro-modulo-prestashop#105]
Boa noite equipe PrestaBR,

O modulo vem funcionando perfeitamente porem estou com uma nova missão.

Preciso configurar split de pagamento no módulo. Estou trabalhando nessa modificação aqui.
Preciso mudar a autenticação para ao invés de utilizar email+token utilize o appid+appkey (D14/D30).
Pra permitir essa autenticação vi que tem bastante coisa implementada no modulo e consegui ativar essas opções más
as sessões não estão sendo criadas com base apenas no appid+appkey+autorizationCode ele me retorna o erro 403-Forbidden sem o autorizationCode ele retorno o erro 401-Unauthorized fiz o fluxo pelo postman pra testar tanto em produção como em sandbox é o mesmo problema afinal esse serviço sessions aceita esse procedimento?

Vocês farão algum trabalho para implementar esse recurso?

**Comment by prestabr** [comment]
Bom Dia 3W3R50N,

Obrigado pelo feedback sobre o funcionamento o módulo!

As opções D14 e D30 fazem parte de um termo de acordo comercial entre a Loja e o PagSeguro. Para a loja utilizar depende de cadastro e aprovação por parte do PagSeguro, e os Tokens só funcionam diretamente em modo Produção. Mesmo termo p/ PS 1.6 e 1.7: https://github.com/pagseguro/pagseguro-modulo-prestashop/blob/master/1.6.x/checkout-transparente/pagseguropro/docs/Termo-de-Acordo-Comercial-PagSeguro.pdf

A API Checkout Transparente não trabalha com Split, a não ser que você faça o Split no módulo para que ele trabalhe com mais de um email+token e possa dicidir qual usar antes de enviar o POST para a API Checkout Transparente. API Split: https://dev.pagseguro.uol.com.br/reference/split

Por enquanto não temos nenhuma previsão para desenvolver soluções voltadas para Split, qualquer novidade sinalizamos aqui no Git.

Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
