### ISSUE TITLE
unknown web session id (hospedagem compartilhada trava sessionid)

### ISSUE THREAD

**Issue by miqueiasazevedo** [pagseguro/pagseguro-modulo-prestashop#106]
Alguém consegue me ajudar com esse erro:
Notice na linha 224 do ficheiro public_html/modules/pagseguropro/pagseguropro.php
[8] Undefined index: appId

Ele está sendo exibido sempre que a página de configuração do módulo é carregada.

Além disso na tela de preenchimento dos dados do cartão é exibida a mensagem "unknown web session id".

**Comment by prestabr** [comment]
Bom Dia miqueiasazevedo,

Obrigado por utilizar o módulo oficial da PagSeguro! :)

> Alguém consegue me ajudar com esse erro:
> Notice na linha 224 do ficheiro public_html/modules/pagseguropro/pagseguropro.php
> [8] Undefined index: appId

Esta linha indica um warning, não é um erro/bug de funcionamento, pode desconsiderá-la.

> 
> Ele está sendo exibido sempre que a página de configuração do módulo é carregada.
> 
> Além disso na tela de preenchimento dos dados do cartão é exibida a mensagem "unknown web session id".

O "unknown web session id" pode ser algo relacionado à sua hospedagem, confere estes tópicos:

https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/96
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/91
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/80 - Solução: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/80#issuecomment-610455265 (talvez seja o mesmo problema que o seu)
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/55

Um problema bastante comum são as permissões erradas nos arquivos e pastas na sua /public_html/modules/pagseguropro/, o ideal é 755 para pastas e 644 para arquivos.

Atenciosamente,
Equipe PrestaBR

**Comment by miqueiasazevedo** [comment]
Opa! 

Primeiramente, muito obrigado pela atenção.

Verifiquei as  pastas e aquivos e estão com as permissões necessárias.

Segue abaixo um print do resultado do console assim que a pagina de checkout é carregada. Talvez forneça mais informações.

![2020-07-10_22-09](https://user-images.githubusercontent.com/43538720/87213254-19e0d900-c2fa-11ea-8bfe-175b6cb43eef.png)

Desde já, muito obrigado!

**Comment by prestabr** [comment]
Boa Noite miqueiasazevedo,

Para usar o sandbox o tipo de credencial precisa ser email+token. Já gerou um token na área sandbox? 

https://sandbox.pagseguro.uol.com.br

![Screenshot at 2020-07-10 22-40-57](https://user-images.githubusercontent.com/7054224/87213908-dd63ac00-c2fe-11ea-9a90-aa7ed211af4a.png)

Conseguiu utilizar o Token em produção?

Atenciosamente,
Equipe PrestaBR

**Comment by miqueiasazevedo** [comment]
Opa!

Já sim!

Estou usando o token da conta sandbox vinculado ao meu e-mail - miqueias.azevedo@hotmail.com.
![image](https://user-images.githubusercontent.com/43538720/87215537-df813700-c30d-11ea-93f3-5a5c879a904e.png)

**Comment by prestabr** [comment]
Boa Tarde miqueiasazevedo,

Você já seguiu essas dicas em 2019 e ainda não conseguiu resolver? https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/55#issuecomment-528502807

Ou você passou a ter problemas novamente depois que:

- trocou de hospedagem?
- atualizou a versão do php?
- instalou outros módulos ou add scripts no layout?
- trocou de tema (layout) na sua loja?

Verifique se a hospedagem está ok tentando gerar o SessionID desta forma:

https://www.minhaloja.com.br/modules/pagseguropro/update.php?acao=session

Exemplo de retorno:

![82821885-3ffe0700-9e7b-11ea-9a67-4d808844a7d1](https://user-images.githubusercontent.com/7054224/87227154-5ef32280-c36f-11ea-9341-427180019c53.png)

Documentação, debug p/ solução de problemas: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Se você já seguiu todas as dicas e já se certificou de cada detalhe e mesmo assim não está dando certo, nossa recomendação é que você tente realizar novos testes em uma outra hospedagem.

Talvez esteja faltando algum detalhe de configuração no Host (Apache ou PHP) por ele ser do tipo compartilhado ou existe algum problema de conectividade.

Para a plataforma PrestaShop o ideal seria utilizar uma hospedagem do tipo VPS. Hospedagens do tipo Compartilhada geralmente são recomendadas para softwares menos complexos, como sites e landingpages que não exigem diversos recursos e processamento de dados.

Atenciosamente,
Equipe PrestaBR

**Comment by miqueiasazevedo** [comment]
Olá, @prestabr !

_>     trocou de hospedagem?_
**Não cheguei a trocar de hospedagem. O problema está ocorrendo desde a instalação.**

_>    atualizou a versão do php?_
**Não**

_>     instalou outros módulos ou add scripts no layout?
>     trocou de tema (layout) na sua loja?_
**Não. O tema permanece o padrão da instalação do prestashop**

_> Verifique se a hospedagem está ok tentando gerar o SessionID desta forma:
> https://www.minhaloja.com.br/modules/pagseguropro/update.php?acao=session_

**Este é o resultado ao tentar executar a ação acima. **
![image](https://user-images.githubusercontent.com/43538720/87230117-d468ee00-c383-11ea-9053-aeb7ecbb3a10.png)

> _Talvez esteja faltando algum detalhe de configuração no Host (Apache ou PHP) por ele ser do tipo compartilhado ou existe algum problema de conectividade._
**Saberia me dizer o que é mais provável que esteja faltando?**

**Comment by prestabr** [comment]
Boa Tarde miqueiasazevedo,

Obrigado por realizar os testes, o problema realmente gira em torno da sua hospedagem.

> Olá, @prestabr !
> 
> > ```
> > trocou de hospedagem?
> > ```
> 
> **Não cheguei a trocar de hospedagem. O problema está ocorrendo desde a instalação.**
> 
> > atualizou a versão do php?
> 
> **Não**
> 
> > ```
> > instalou outros módulos ou add scripts no layout?
> > trocou de tema (layout) na sua loja?
> > ```
> 
> **Não. O tema permanece o padrão da instalação do prestashop**
> 
> > Verifique se a hospedagem está ok tentando gerar o SessionID desta forma:
> > https://www.minhaloja.com.br/modules/pagseguropro/update.php?acao=session
> 
> **Este é o resultado ao tentar executar a ação acima. **
> ![image](https://user-images.githubusercontent.com/43538720/87230117-d468ee00-c383-11ea-9053-aeb7ecbb3a10.png)
> 
> > Talvez esteja faltando algum detalhe de configuração no Host (Apache ou PHP) por ele ser do tipo compartilhado ou existe algum problema de conectividade.
> 
> **Saberia me dizer o que é mais provável que esteja faltando?**

Pode ser qualquer coisa dentro de diversas possibilidades, exemplo:

- Hospedagem lenta;
- Hospedagem com algum tipo de bloqueio, talvez até firewall;
- Hospedagem com algum ou vários pacotes faltando no apache ou php;
- Etc.

O ideal seria partir para outra hospedagem, de preferência uma do tipo VPS.

Atenciosamente,
Equipe PrestaBR
