### ISSUE TITLE
Erros ao acessar Módulo e ao finalizar pedido na loja (loja com debug ativo em modo de produção)

### ISSUE THREAD

**Issue by rafaelsilvabra** [pagseguro/pagseguro-modulo-prestashop#107]
Oi amigos,

Estou tentando usar o modulo de vocês no meu presta 1.6 porém estou com 2 problemas.
1) Ao finalizar o pedido de pagamento(boleto por exemplo) tudo quebra onde deveria carregar as informações do boleto para o cliente, mas os dados são enviados ao pagseguro e o cliente recebe por email a cobranca padrão do pagseguro mas na loja da essa quebra.
2) Toda vez que acesso as configurações do módulo, aparece o alerta de erro. Mesmo eu deletando e reinstalando tudo continua ambos os erros.

Podem ajudar?
Obrigado.

![erros_gerarpagamento](https://user-images.githubusercontent.com/31866021/87434627-15017b00-c5c1-11ea-8adb-915e6fb2f405.jpg)
![erro_modulo](https://user-images.githubusercontent.com/31866021/87434936-76294e80-c5c1-11ea-8705-c9669f52b81c.png)

**Comment by prestabr** [comment]
Bom Dia rafaelsilvabra,

> Oi amigos,
> 
> Estou tentando usar o modulo de vocês no meu presta 1.6 porém estou com 2 problemas.
> 
> 1. Ao finalizar o pedido de pagamento(boleto por exemplo) tudo quebra onde deveria carregar as informações do boleto para o cliente, mas os dados são enviados ao pagseguro e o cliente recebe por email a cobranca padrão do pagseguro mas na loja da essa quebra.

Desativa o debug da sua loja em /config/defines.inc.php:

```
/* Debug only */
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', false);
}
```

O módulo em modo de produção com a loja em modo debug acaba gerando problemas. O debug pode limitar a coleta de dados e redirecionamentos. Basicamente o boleto executa um redirect no validation pra processar o inset e posterior tela de confirmação de pedido.

> 2. Toda vez que acesso as configurações do módulo, aparece o alerta de erro. Mesmo eu deletando e reinstalando tudo continua ambos os erros.
> 
> Podem ajudar?
> Obrigado.
> 
> ![erros_gerarpagamento](https://user-images.githubusercontent.com/31866021/87434627-15017b00-c5c1-11ea-8adb-915e6fb2f405.jpg)
> ![erro_modulo](https://user-images.githubusercontent.com/31866021/87434936-76294e80-c5c1-11ea-8705-c9669f52b81c.png)

Esse alerta é apenas um warning, não é um erro/bug, pode desconsierar. Na próxima update removemos este warning. Você sempre vê a mensagem por conta do debug ativo na loja.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
HUmmmm verdade. eu desativei e sumiu os warning e voltou a gerar os dados certinho.

**Comment by prestabr** [comment]
Olá rafaelsilvabra,

Ótimo, obrigado pelo feedback! Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
