### ISSUE TITLE
Simbolo ao errar numero do cartao ou cpf (loja com problemas de layout css/js)

### ISSUE THREAD

**Issue by Limongii** [pagseguro/pagseguro-modulo-prestashop#108]
Boa noite. No tema padrão do prestashop funciona perfeitamente, mas ao colocar o tema novo comprado aparece um símbolo de X em vermelho toda vez que erro o cpf  ou numero do cartão, e quando ta certo um símbolo de correto verde. 

<a href="https://ibb.co/rHrLHRd"><img src="https://i.ibb.co/rHrLHRd/123.png" alt="123" border="0"></a>

**Comment by prestabr** [comment]
Boa Noite Limongii,

Essa área valida os campos em tempo real via JavaScript. Exibir o icone repetido ou não correspondente com ação não é o comportamento esperado, isso indica algum conflito de JavaScript no seu tema.

Você já conferiu o inspetor de elementos do seu navegador em busca de conflitos?

Confere essa dica: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Atenciosamente,
Equipe PrestaBR

**Comment by Limongii** [comment]
Boa noite, verifiquei e fica conforme imagem abaixo. 

<a href="https://ibb.co/Mgj216R"><img src="https://i.ibb.co/Mgj216R/1233.png" alt="1233" border="0"></a>

**Comment by prestabr** [comment]
Olá Limongii,

Obrigado pelo print com os detalhes.

As mensagens indicando "unknown web session id" ou "o token web é inválido" sinalizam problemas maiores, englobando a hospedagem.

Por favor, verifique se a hospedagem está ok tentando gerar o SessionID desta forma:

https://www.minhaloja.com.br/modules/pagseguropro/update.php?acao=session

Exemplo de retorno:

![87227154-5ef32280-c36f-11ea-9341-427180019c53](https://user-images.githubusercontent.com/7054224/87484177-e65cc200-c60b-11ea-8a5c-263dc4f784a7.png)


Obtendo uma resposta negativa o ideal seria partir para outra hospedagem, de preferência uma do tipo VPS. Por favor, confere esta issue (é a mesma questão): https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/106#issuecomment-657242995

Atenciosamente,
Equipe PrestaBR

**Comment by Limongii** [comment]
<a href="https://ibb.co/JpY9QJY"><img src="https://i.ibb.co/JpY9QJY/1.png" alt="1" border="0"></a> <a href="https://ibb.co/3r4J28D"><img src="https://i.ibb.co/3r4J28D/2.png" alt="2" border="0"></a>


Infelizmente não sei o que pode ser.

**Comment by prestabr** [comment]
Olá Limongii,

> [![1](https://camo.githubusercontent.com/6e1dd2b64796e1ecc20949d4dac28dc57f92d5a3/68747470733a2f2f692e6962622e636f2f4a705939514a592f312e706e67)](https://ibb.co/JpY9QJY) [![2](https://camo.githubusercontent.com/558233a29da43b68037efa4efed6f81e779f20d8/68747470733a2f2f692e6962622e636f2f3372344a3238442f322e706e67)](https://ibb.co/3r4J28D)
> 
> Infelizmente não sei o que pode ser.

Aparentemente agora o módulo está funcional, mas o conflito de JavaScript ainda existe. No seu backoffice, tenta desativar o CCC do JS, geralmente quando tem conflito a compressão não fica legal. Acessa "Parâmetros Avançados > Desempenho > CCC (Combinação, Compressão e Cache)".

Você está rodando a loja em localhost?! Tenta colocar tudo para funcionar em um servidor web do tipo VPS, coloca o módulo em modo produção com o token também. Tendo uma url de acesso em mãos (www.meusite.com.br), por favor, posta aqui pra gente tentar acessar e testar para te ajudar.

Atenciosamente,
Equipe PrestaBR

**Comment by Limongii** [comment]
Boa noite. 
http://lojadoadson-com-br.umbler.net/br/ 

Hospedado em um vps, mas continua com o mesmo erro. 
Pagina de ADM
lojadoadson-com-br.umbler.net/admin107onftmr/

email: limongi.proxy@gmail.com
senha: Sptgsnsdc123@

Os arquivos lá sao apenas para testes, não tem problema alterar ou outra pessoa acessar.

**Comment by prestabr** [comment]
Bom Dia Limongii,

Obrigado pelos dados de acesso.

O admin não faz o login:
![Screenshot at 2020-07-15 09-33-40](https://user-images.githubusercontent.com/7054224/87545459-5a37b280-c67e-11ea-937e-ea15ecc0863a.png)

Ao acessar o frontoffice verificamos que a hospedagem é muito lenta (10-15s ou mais pra terminar de carregar qualquer página). O ideal é utilizar um servidor do tipo VPS, algo com mais capacidade de processamento.

Também não localizamos o padrão de cadastro brasileiro, campo para informar o cpf no cadastro, que é obrigatório para processar pagamentos.

Tecnicamente o módulo está 100% funcional em sua tela de checkout, confere que o "Session ID", "SenderHash" e outros detalhes estão sendo carregados corretamente conforme indicado na documentação: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Sobre o problema do icone na tela de checkout é uma questão de layout ou customizações de css, recomendamos que você compare com o tema original e faça as correções ou procure o auxílio de um profissional.

![Screenshot at 2020-07-15 09-43-19](https://user-images.githubusercontent.com/7054224/87546787-7dfbf800-c680-11ea-8af8-f0ec7d9187b7.png)


Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
