### ISSUE TITLE
prazo de vencimento do BOLETO

### ISSUE THREAD

**Issue by rafachiarello** [pagseguro/pagseguro-modulo-prestashop#109]
Olá!
Primeiramente, agradeço o módulo disponibilizado que tem funcionado muito bem em minha loja.
Agora, gostaria de esclarecer uma dúvida referente ao prazo de vencimento do Boleto que é gerado, se é possível reduzir para 1 dia útil?
Já tentei de todas as formas fazer esta alteração diretamente no painel de acesso da minha conta PagSeguro, porém sem sucesso. Não encontrei esta opção de personalização disponível!
Grato, no aguardo.
Att.
Rafael

**Comment by prestabr** [comment]
Boa Noite rafachiarello,

Agradecemos o seu feedback! :)

O prazo mínimo de vencimento é de 2 dias úteis e +4 de expiração (que é obrigatório) para cancelamento automático via API.

Você pode solicitar a alteração entrando em contato com o gerente da sua conta ou pela central de atendimento https://faq.pagseguro.uol.com.br/ligue-central-atendimento#rmcl.

Atenciosamente,
Equipe PrestaBR
