### ISSUE TITLE
Prestashop 1.6.1.24 

### ISSUE THREAD

**Issue by consule** [pagseguro/pagseguro-modulo-prestashop#110]
Tenho o Prestashop 1.6.1.24 e fiz todas as configurações e não aparece para meu cliente a opção para pagamento com PagSeguro. Ao salvar aparece a  mensagem em vermelho conforme imagem. 

![salvar](https://user-images.githubusercontent.com/7459560/90410230-7913d500-e080-11ea-9a00-e7deb8618cfb.png)

**Comment by prestabr** [comment]
Boa Tarde consule,

> Tenho o Prestashop 1.6.1.24 e fiz todas as configurações e não aparece para meu cliente a opção para pagamento com PagSeguro. 

Já verificou se o módulo está com alguma restrição de moeda, grupo ou país na tab "Módulos > Pagamento"?

>Ao salvar aparece a mensagem em vermelho conforme imagem.
> 
> ![salvar](https://user-images.githubusercontent.com/7459560/90410230-7913d500-e080-11ea-9a00-e7deb8618cfb.png)

Não conseguimos reproduzir esta mensagem em nosso ambiente de testes e homologação. Ela parece ser genérica, de algum conflito em sua loja ou de alguma tradução errada.

Este módulo não depende e não utiliza recursos de terceiros no sistema. Compatibilidade: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#compatibilidade

Debug para solução de problemas:

PS 1.6.x: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Atenciosamente,
Equipe PrestaBR

**Comment by consule** [comment]
Veja, realmente não está marcado, como devo fazer para habilitar e marcar a opção?

![pagamento](https://user-images.githubusercontent.com/7459560/90431263-2269c380-e09f-11ea-92fb-50b6c5698560.png)

**Comment by prestabr** [comment]
Olá consule,

Estas configurações de vinculos entre país, grupo e moeda são 100% automatizadas nas PS 1.6. Quando o módulo é instalado o sistema se encarrega de criar os vinculos nessa área.

> Veja, realmente não está marcado, como devo fazer para habilitar e marcar a opção?
> 
> ![moeda](https://user-images.githubusercontent.com/7459560/90431596-a9b73700-e09f-11ea-9740-253b749fc418.png)
> 

Esta configuração está ok, indica que a moeda está vinculada ao módulo.

> ![pagamento](https://user-images.githubusercontent.com/7459560/90431263-2269c380-e09f-11ea-92fb-50b6c5698560.png)

No país o vinculo também deveria existir, assim como toda a lista de países. Exemplo:

![Screenshot at 2020-08-17 16-15-36](https://user-images.githubusercontent.com/7054224/90435106-e76a8e80-e0a4-11ea-8aa2-ac2b54871878.png)

Se os demais paises não existem isso indica que houve alguma manipulação no banco de dados e ou core/overrides, alterando o sistema original, ocasionando a dificuldade.

Você tem acesso ao seu banco de dados da loja virtual? Se tiver, pode seguir este passo-a-passo para tentar fazer o vinculo manualmente:

a) Consulta o módulo na tabela "ps_modules":

`SELECT * FROM `ps_module` WHERE name='pagseguropro';`

![Screenshot at 2020-08-17 16-20-04](https://user-images.githubusercontent.com/7054224/90435678-b0e14380-e0a5-11ea-866e-66995ead196e.png)

b) Vincula o módulo ao país na tabela "ps_country":

`INSERT INTO `ps_module_country` (`id_module`, `id_shop`, `id_country`) VALUES ('68', '1', '58');`

_Altera o 68 pelo número do seu módulo._

Por favor, posta aqui pra gente se você já consegue visualizar o módulo no seu checkout.

Atenciosamente,
Equipe PrestaBR

**Comment by consule** [comment]
Fiz o seguinte. 

A) Selecionei a linha da tabela `as_module` conforme sua orientação, o ID do modulo do PagSeguro é 113
B) Fui na tabela `as_country` e peguei o `id_country` com o valor de 245
C) Na tabela `as_module_country` já existia a linha com o `id_module` igual a 113 e `id_country` igual a 245. 

Mesmo assim não aparece no checkout a opção do pagSeguro para fazer o pagamento e finalizar o pedido. 

![detalhes](https://user-images.githubusercontent.com/7459560/90440010-ef2e3100-e0ac-11ea-9eb7-e8525cbde329.png)

**Comment by prestabr** [comment]
Olá consule,

Na Prestashop, o Brasil é sempre o ID 58 e as configurações padrão do país são essas (sistema original):

![Screenshot at 2020-08-17 17-26-43](https://user-images.githubusercontent.com/7054224/90441198-ecccd680-e0ae-11ea-90ce-d107a654b271.png)

A sua loja está mexida/modificada, os IDs básicos de países, regiões e uf não batem com a configuração original do sistema, nem o ISO code do Brasil que não é DF e sim BR. O exemplo que demos era apenas demonstrativo caso você esteja familiarizado com a estrutura da PrestaShop. 

A sugestão é que você tente instalar uma nova loja, limpa e original, sem customizações desconhecidas e tente instalar o módulo para vê-lo funcionando corretamente. Apartir dai você pode comparar com a sua loja em produção e tentar localizar as divergências que ocasionam os problemas de funcionamento em sua loja. Outra opção, se for viável, é procurar o auxílio de um profissional.

Atenciosamente,
Equipe PrestaBR
