### ISSUE TITLE
Mensagem após finalizar pagamento (dados ausentes no cadastro do cliente na loja)

### ISSUE THREAD

**Issue by consule** [pagseguro/pagseguro-modulo-prestashop#111]
Senhores, 

Quando informo todos os dados na tela de pagamento e clico em "Pagar" é me retornado uma mensagem conforme a imagem. 

Versão: 1.6 

-- Log de erro ---
(125) DATA: 25/08/2020 09:54:42 - TIPO: ERROR - MÉTODO: POST
ID DO CARRINHO: 2203

URL CHAMADA
https://ws.sandbox.pagseguro.uol.com.br/v2/sessions

DADOS ENVIADOS
{
    "email": "daniela@atenassuprimentos.com.br",
    "token": "**editado PrestaBR - aqui vai o token**"
}

RESPOSTA DA API
<?xml version="1.0"?>
-- Fim do log de erro --

![WhatsApp Image 2020-08-25 at 09 33 10](https://user-images.githubusercontent.com/7459560/91290945-b3f5c700-e76a-11ea-8de9-ecb8136e7e2f.jpeg)

**Comment by prestabr** [comment]
Boa Tarde consule,

Ótimo que tenha conseguido resolver o problema na issue https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/110 ! :)

Este log que você verificou é referente ao início da sessão na tela de pagamento, você precisa pegar o log do payload para analisar a causa do problema. O payload são aos dados enviados para tentar processar o pagamento.

Esta mensagem "Forma de pagamento temporáriamente indisponível" é genérica, geralmente indica algum dado ausente no cadastro do cliente, não tratado anteriormente na tela de cadastro na loja.

Leitura rápida, confere como verificar os logs: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/75#issuecomment-567057058

Para evitar problemas com o processamento do pagamento sugerimos que torne obrigatório os seguintes campos no cadastro do cliente: cpf, endereço, numeral do endereço, bairro, cidade, estado, telefone ou celular.

**Importante:**

Nunca divulgue o seu TOKEN para ninguém, nem publique na Web, seja aqui no Git ou em fórums. Sugerimos que acesse sua conta na PagSeguro e gere um novo Token por questão de segurança. https://pagseguro.uol.com.br/preferencias/integracoes.jhtml

Atenciosamente,
Equipe PrestaBR

**Comment by consule** [comment]
Bom dia, 

Consegui pegar o log correto e fiz o ajuste. Porém ainda persiste dar duas mensagens, podem ajudarw

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<errors>
  <error>
    <code>53022</code>
    <message>shipping address postal code is required.</message>
  </error>
  <error>
    <code>53053</code>
    <message>billing address postal code is required.</message>
  </error>
</errors>

**Comment by prestabr** [comment]
Bom Dia consule,

> Bom dia,
> 
> Consegui pegar o log correto e fiz o ajuste. Porém ainda persiste dar duas mensagens, podem ajudar:
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <errors>
>   <error>
>     <code>53022</code>
>     <message>shipping address postal code is required.</message>
>   </error>
>   <error>
>     <code>53053</code>
>     <message>billing address postal code is required.</message>
>   </error>
> </errors>
> ```

Estes logs indicam que o cliente que tentou efetuar o pedido não está com o CEP (postcode) cadastrado no seu endereço. Acessa o cadastro do cliente e informa o CEP no padrão "NNNNN-NNN".

Para tornar o CEP obrigatório acessa "Clientes > Endereços", rola a página até o final e clica em "Defina os campos obrigatórios desta secção", seleciona os campos obrigatórios e Salva.

> ![brasil](https://user-images.githubusercontent.com/7459560/91434424-2cc45400-e83b-11ea-92d1-1d551e1f0f54.png)

Esse print não tem relação com o Log, mas sugerimos que atualize o seu código ISO de DF para BR.

Atenciosamente,
Equipe PrestaBR

**Comment by consule** [comment]
Só de obrigar o CEP já funcionou. 

Obrigado, pode fechar a issue
![Sem título](https://user-images.githubusercontent.com/7459560/91459191-bdf7f280-e85c-11ea-8394-c5f8fe12ef12.png)

**Comment by prestabr** [comment]
Olá consule,

Perfeito, obrigado pelo feedback! Qualquer dúvida ou problema, por favor, fique à vontade para abrir uma nova issue.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
