### ISSUE TITLE
Formas de pagamento

### ISSUE THREAD

**Issue by SSGoveia** [pagseguro/pagseguro-modulo-prestashop#112]
O módulo está instalado e configurado, mas não aparece na seção Formas de Pagamentos.
PrestaShop 1.7.6.7

**Comment by prestabr** [comment]
Boa Noite SSGoveia,

Obrigado por utilizar o módulo oficial da PagSeguro! :)

Confere essa dica, parece ser o mesmo problema: "Utilizando a PrestaShop 1.7, acesse no Back Office a tab "Pagamento > Preferências > Restrições de transportadora" e verifique se as transportadoras estão vinculadas à forma de pagamento." https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/79#issuecomment-600285084

Caso não resolva para você, por favor, passa pra gente mais detalhes sobre o problema (se possível envie prints). Utilize a ferramenta de Debug: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Atenciosamente,
Equipe PrestaBR

**Comment by SSGoveia** [comment]
Deu certo, eram as configurações de restrição.
Meu produto é somente online (cursos) e por isso não tinha transportadora.

**Comment by prestabr** [comment]
Boa Tarde SSGoveia,

Perfeito, obrigado pelo feedback!

Para evitar problemas com o processamento do pagamento sugerimos que torne obrigatório os seguintes campos no cadastro do cliente: cpf, endereço, numeral do endereço, bairro, cidade, estado (uf), telefone ou celular.

Acessa "Clientes > Endereços", rola a página até o final e clica em "Definir os campos obrigatórios para esta seção", seleciona os campos obrigatórios e Salva.

Qualquer dúvida ou problema, por favor, fique à vontade para abrir uma nova issue.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
