### ISSUE TITLE
Quantidade máxima de parcelas

### ISSUE THREAD

**Issue by consule** [pagseguro/pagseguro-modulo-prestashop#113]
Senhores, 

Na minha loja o valor minimo para parcelar é de 600 reais onde este valor informei no campo: 

`Valor da parcela mínima 600.00 `

Em  **Quantidade máxima de parcelas**  informei que pode ser parcelado em até 2x. 

Um cliente colocou no carrinho **`R$ 1507,00`** e só aparece a opção de 2x. 

Não exibe a opção de 1x porque?

**Comment by prestabr** [comment]
Bom Dia consule,

Não exibe porque é um bug e está previsto para correção, em nosso backlog, para a próxima update. Se o total do pedido for maior do que R$ 1.000,00 a parcela de 1x não é exibida começando a contagem a partir da 2x parcela.

Esta correção é simples, você pode aplicar no módulo em sua loja sem precisar aguardar a update, faz o seguinte:

Na linha 188 do arquivo pagseguropro.js https://github.com/pagseguro/pagseguro-modulo-prestashop/blob/master/1.6.x/checkout-transparente/pagseguropro/js/pagseguropro.js

Remove:
`if (valor >= parcelaMinima) {`

Add:
`if (optionValor >= parcelaMinima) {`

Salva o arquivo, na loja navega até o menu "Parâmetros Avançados > Desemplenho" e clica em "Limpar Cache" no canto superior direito da tela.

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR

**Comment by consule** [comment]
A Correção deu certo! 

Ainda sobre o pagamento queria saber o seguinte:

Quando coloco 600 na parcela minima e o cliente que comprar 599, esta compra não é permitida? 

Queria o seguinte: Se alguém comprar 10 reais que a venda fosse feita, mais que para parcelar ele teria que comprar acima de 600 reais. 

Aguardo retorno.

**Comment by prestabr** [comment]
Boa Noite consule,

> A Correção deu certo!

Ótimo, obrigado pela confirmação.

> Ainda sobre o pagamento queria saber o seguinte:
> 
> Quando coloco 600 na parcela minima e o cliente que comprar 599, esta compra não é permitida?
>
> Queria o seguinte: Se alguém comprar 10 reais que a venda fosse feita, mais que para parcelar ele teria que comprar acima de 600 reais.

Não é permitida, se a parcela mínima é R$ 600 não tem como processar nada abaixo disso, o objetivo da parcela mínima é esse. O cliente não consegue pagar na tela de checkout porque não existe nenhuma parcela para selecionar.

Se a parcela mínima é R$ 600 obrigatóriamente o seu produto mais barato deve custar R$ 600 e não R$ 10 ou R$ 599.

> Aguardo retorno.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
