### ISSUE TITLE
Atenção - Configuração de CPF:

### ISSUE THREAD

**Issue by mainbrainapp** [pagseguro/pagseguro-modulo-prestashop#114]
Poderiam me ajudar? Depois que instalei o modulo do pagseguro fica gerando o alerta abaixo. Saberiam como resolver ?

Existem 2 alertas:
Módulo Oficial PagSeguro - Checkout Transparente - PS 1.7.x

---

Atenção - Configuração de CPF:

Nenhuma configuração de CPF foi encontrada em sua loja para que o cliente possa preencher durante o cadastrado, o CPF é obrigatório para processar pagamentos. Os módulos de integração do PagSeguro pra PrestaShop 1.6.x e 1.7.x são compatíveis com os principais módulos de cadastro brasileiro. Diversas opções podem ser encontradas na web pesquisando pelo termo "padrão de cadastro brasileiro prestashop".

**Comment by prestabr** [comment]
Bom Dia mainbrainapp,

Obrigado por utilizar o módulo oficial em sua loja! :)

Este alerta serve para informar/orientar sobre configurações básicas e boas práticas na loja virtual, no caso sinaliza que a loja não captura o CPF do cliente no momento do cadastro. Isto não impede que a loja processe pagamentos porque o módulo exige o preenchimento na tela de checkout.

Caso queira capturar o CPF e torná-lo obrigatório na loja sugerimos instalar um módulo para a finalidade, diversas opções podem ser encontradas na web pesquisando pelo termo "padrão de cadastro brasileiro prestashop".

Você pode desativar este alerta desabilitando a opção de debug do módulo:

PS 1.6: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

PS 1.7: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Atenciosamente,
Equipe PrestaBR
