### ISSUE TITLE
Não foi possível obter a Bandeira do cartão. Verifique se o número está correto.

### ISSUE THREAD

**Issue by koutch12** [pagseguro/pagseguro-modulo-prestashop#115]
Olá Alguem Pode Me Ajudar Por Favor !!!!!

**Comment by prestabr** [comment]
Bom Dia koutch12,

Obrigado por utilizar o módulo oficial em sua loja! :)

Consegue nos passar mais detalhes, como um print ou os 6 primeiros dígitos do cartão pra gente verificar?

Para pagamentos via Cartão de Crédito só é aceita a modalidade Crédito, cartões de débito ou de dupla função (débito e crédito) não são aceitos.

Atenciosamente,
Equipe PrestaBR
