### ISSUE TITLE
(1/1) ContextErrorExceptionNotice: Undefined index: this_path (problemas de configuração na hospedagem)

### ISSUE THREAD

**Issue by jagunsow** [pagseguro/pagseguro-modulo-prestashop#116]
php 7.2
Prestashop 1.7.6.8

(1/1) ContextErrorExceptionNotice: Undefined index: this_path
--
in 4d1bbf96398226a5a66967564e7855d22a39e555_2.module.pagseguroproviewstemplate.php line 58
at content_5f9bfc122db643_08342817(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 40
at SmartyDevTemplateCore->fetch()in Module.php line 2447
at ModuleCore->fetch('module:pagseguropro/views/templates/hook/payment_top.tpl')in pagseguropro.php line 2211
at PagSeguroPro->hookDisplayPaymentTop(array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 970
at HookCore::coreCallHook(object(PagSeguroPro), 'hookdisplayPaymentTop', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 355
at HookCore::callHookOn(object(PagSeguroPro), 'displayPaymentTop', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 907
at HookCore::exec('displayPaymentTop', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1), null)in smarty.config.inc.php line 167
at smartyHook(array('h' => 'displayPaymentTop'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83

**Comment by prestabr** [comment]
Boa Tarde jagunsow,

Obrigado por utilizar o módulo oficial em sua loja! :)

Criamos um ambiente de testes nas mesmas condições (php e versão da loja), fizemos alguns testes de compras, mas não conseguimos reproduzir o problema, segue detalhes:

PHP v.7.2.34:
![Screenshot at 2020-10-30 16-56-33](https://user-images.githubusercontent.com/7054224/97751486-2c616700-1ad1-11eb-8ac4-4f5988126f8a.png)

PrestaShop, versão mais recente, v1.7.6.8:
![Screenshot at 2020-10-30 16-59-26](https://user-images.githubusercontent.com/7054224/97751586-49963580-1ad1-11eb-9dd3-4278a47dbda9.png)
Download: https://www.prestashop.com/pt/versoes-anteriores (todas as versões estão disponíveis no link, incluindo as betas).

Tela de checkout:
![Screenshot at 2020-10-30 17-02-57](https://user-images.githubusercontent.com/7054224/97751850-c6c1aa80-1ad1-11eb-86af-760592c60f9c.png)

Pedido de teste via Boleto:
![Screenshot at 2020-10-30 17-06-30](https://user-images.githubusercontent.com/7054224/97752283-79920880-1ad2-11eb-97a0-9c27d19caeb1.png)

> php 7.2
> Prestashop 1.7.6.8
> 
> ## (1/1) ContextErrorExceptionNotice: Undefined index: this_path
> in 4d1bbf96398226a5a66967564e7855d22a39e555_2.module.pagseguroproviewstemplate.php line 58
> at content_5f9bfc122db643_08342817(object(SmartyDevTemplate))in smarty_template_resource_base.php line 123
> at Smarty_Template_Resource_Base->getRenderedTemplateCode(object(SmartyDevTemplate))in smarty_template_compiled.php line 114
> at Smarty_Template_Compiled->render(object(SmartyDevTemplate))in smarty_internal_template.php line 216
> at Smarty_Internal_Template->render(false, 0)in smarty_internal_templatebase.php line 232
> at Smarty_Internal_TemplateBase->_execute(object(SmartyDevTemplate), null, null, null, 0)in smarty_internal_templatebase.php line 116
> at Smarty_Internal_TemplateBase->fetch(null, null, null, null, false, true, false)in SmartyDevTemplate.php line 40
> at SmartyDevTemplateCore->fetch()in Module.php line 2447
> at ModuleCore->fetch('module:pagseguropro/views/templates/hook/payment_top.tpl')in pagseguropro.php line 2211
> at PagSeguroPro->hookDisplayPaymentTop(array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 970
> at HookCore::coreCallHook(object(PagSeguroPro), 'hookdisplayPaymentTop', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 355
> at HookCore::callHookOn(object(PagSeguroPro), 'displayPaymentTop', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1))in Hook.php line 907
> at HookCore::exec('displayPaymentTop', array('smarty' => object(SmartyDevTemplate), 'cookie' => object(Cookie), 'cart' => object(Cart), 'altern' => 1), null)in smarty.config.inc.php line 167
> at smartyHook(array('h' => 'displayPaymentTop'), object(SmartyDevTemplate))in SmartyLazyRegister.php line 83

Este erro é bastante genérico, não indica um problema específico do módulo e/ou questões de compatibilidade com o mesmo.

Sugerimos que verifique as permissões em sua hospedagem, o ideal é 755 para diretórios e 644 para arquivos no geral. Verifique se o cache da sua loja está limpo e não enfrenta dificuldades de escrita e/ou leitura. Se a loja estiver trabalhando com overrides ou layout customizado, tente realizar os testes em uma versão original do sistema (sem alterações). Se puder, tente também realizar o teste em outra hospedagem.

Atenciosamente,
Equipe PrestaBR

**Comment by jagunsow** [comment]
Oi, obrigado pela resposta, então deve ser algo específico com meu E-commerce, vou  ver se encontro o que é, se encontrar atualizo aqui para servir para outras pessoas.

**Comment by prestabr** [comment]
Boa Tarde jagunsow,

Obrigado pelo feedback.

A PrestaShop na versão 1.7 é bem robusta e o Symfony exige bastante da hospedagem. A maior parte dos problemas de funcionamento da loja pode ser resolvido com uma hospedagem bem configurada, com mais performance, algo do tipo VPS seria o ideal.

Tenta ir por etapas para você ir descartando as possibildiades. Começa tentando trocar de hospedagem, depois verifica o sistema (overrides/layout e alterações no core se houver), cache, instalação, módulo, etc.

Por favor, sinta-se à vontade para voltar aqui no post e compartilhar a solução do seu problema com o público.

Atenciosamente,
Equipe PrestaBR
