### ISSUE TITLE
Instabilidade Host (criação de pedido), dúvida sobre logs, atualização do módulo, etc.

### ISSUE THREAD

**Issue by rafachiarello** [pagseguro/pagseguro-modulo-prestashop#117]
Olá!
Venho utilizando em minha loja o módulo PagSeguro - Checkout Transparente, desenvolvido pela PRESTABR, há um bom tempo e normalmente com êxito nas transações realizadas. A propósito, o trabalho de vocês é excelente, assim como o suporte prestado! Muito obrigado! 
Ocorre que m pedido realizado em minha loja com acesso via link do Instagram e a partir de um smartphone com SO Android resultou em um erro que, apesar de a transação de pagamento ser concluída com sucesso, não houve o retorno da informação pela aplicação para a respectiva conclusão do carrinho de compras originado no processo, pelo cliente.
Dessa forma, o pagamento foi concluído e recebido, mas o respectivo carrinho de compras que originou a transação restou sem a finalização da compra.
Relato do cliente: "Eu acessei o site via link no Instagram pelo meu celular Android. Fiz todo o processo da compra e depois a tela ficou processando por vários minutos. Nesse tempo teve o desconto no meu cartão e recebi o email de confirmação, porém a tela continuou em loading. Após vários minutos assim abri pelo meu note o site e o carrinho estava vazio porém não constava a compra no histórico."

Minha loja opera com o Prestashop em um servidor Linux VPN Hostgator exclusivo:
Versão do PrestaShop: 1.7.6.2
Versão do Apache | 2.4.46
Versão do PHP | 7.2.34
Versão do MySQL | 5.7.32
Arquitetura | x86_64
Sistema operacional | linux
Caminho para Perl | /usr/bin/perl
Versão do Perl | 5.16.3
Versão do kernel | 3.10.0-1160.6.1.el7.x86_64

Versão PagSeguro - Checkout Transparente v.1.1.0

Analisando os registros  de Logs do módulo não pude identificar algum erro, por isso venho aqui buscar a ajuda de vocês para tentar identificar o que pode ter ocasionado este problema.

Segue print do registro de logs do módulo Pagseguro onde aparece o problema em questão:
![image](https://user-images.githubusercontent.com/60196289/101671692-97d51780-3a33-11eb-84b6-e5a716b2a26b.png)

(969) 
![image](https://user-images.githubusercontent.com/60196289/101674740-a58c9c00-3a37-11eb-9f18-097cfd3d8e53.png)

(970)
![image](https://user-images.githubusercontent.com/60196289/101674877-cead2c80-3a37-11eb-9ee8-a6fd6b5bae43.png)

(971) 
![image](https://user-images.githubusercontent.com/60196289/101675328-6e6aba80-3a38-11eb-82da-7d91f5aae8e2.png)
![image](https://user-images.githubusercontent.com/60196289/101675469-9bb76880-3a38-11eb-8476-234aeb09ce3e.png)

(972)
![image](https://user-images.githubusercontent.com/60196289/101675544-b5f14680-3a38-11eb-9b1c-83e2cd664d6a.png)

(973) 
![image](https://user-images.githubusercontent.com/60196289/101676114-7d05a180-3a39-11eb-9209-c415bc539b5d.png)

(974) 
![image](https://user-images.githubusercontent.com/60196289/101676168-93abf880-3a39-11eb-9047-d04d2d5f4224.png)

(975) 
![image](https://user-images.githubusercontent.com/60196289/101675869-20a28200-3a39-11eb-86d7-02b839132478.png)

(976) 
![image](https://user-images.githubusercontent.com/60196289/101676306-c1913d00-3a39-11eb-8d1a-615d4e8aa3d9.png)

(977) 
![image](https://user-images.githubusercontent.com/60196289/101676381-dcfc4800-3a39-11eb-84c2-133709c242c4.png)

(978)
![image](https://user-images.githubusercontent.com/60196289/101676451-f43b3580-3a39-11eb-8898-af557d277e94.png)

(979)
![image](https://user-images.githubusercontent.com/60196289/101676583-1d5bc600-3a3a-11eb-96f0-9ae48eb224b4.png)

(980) 
![image](https://user-images.githubusercontent.com/60196289/101676638-319fc300-3a3a-11eb-9eeb-066b5242639d.png)

(981)
![image](https://user-images.githubusercontent.com/60196289/101676826-775c8b80-3a3a-11eb-9be2-f31510359c1b.png)
![image](https://user-images.githubusercontent.com/60196289/101676941-a410a300-3a3a-11eb-88de-4408c2bc3cbd.png)

(982)
![image](https://user-images.githubusercontent.com/60196289/101677019-c30f3500-3a3a-11eb-9efd-8e188eea0c60.png)

Por fim, outra coisa que notei a partir desse problema, verificando os logs, é que a aplicação está realizando algumas chamadas referente a pedidos anteriores já concluídos, como se vê neste print:
![image](https://user-images.githubusercontent.com/60196289/101677603-87c13600-3a3b-11eb-94d7-138fe94a93c3.png)

Não sei qual a finalidade disso e até que ponto pode ser considerado um problema, mas deixo o registro para análise.

Grato desde já, fico a disposição para prestar maiores informações.

**Comment by prestabr** [comment]
Boa Tarde rafachiarello,

Agradecemos o seu feedback! :)

O cliente vir de link direto (url do seu site) ou via link externo de referência (google, facebook, instagram, etc) não muda nada e é irrelevante para o processamento do pagamento, o mesmo vale para o tipo de dispositivo (Desktop/Tablet ou Mobile) porque o mecanismo de processamento é o mesmo.

Esse tipo de problema, da loja não criar o pedido a partir do carrinho e o mesmo constar apenas no PagSeguro, geralmente ocorre quando há alguma falha ou atraso/lentidão incomum na comunicação entre a loja (hospedagem) e o PagSeguro.

Nestes casos você pode criar o pedido na loja a partir do carrinho de compras pesquisando pela referência, o prefixo é o ID do carrinho na loja. No backoffice, acessa "Clientes > Carrinho de Compras", acessa o carrinho e clica em "Criar um pedido a partir do carrinho".

Exemplo
![Screenshot at 2020-12-09 16-39-48](https://user-images.githubusercontent.com/7054224/101679858-a83ebf80-3a3e-11eb-8c15-e032b5946371.png)

Se puder, tenta atualizar o módulo para a versão mais recente v.1.2.0 - changelog: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#changelog

Dica para analisar logs: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/75#issuecomment-567057058

Sobre "chamadas referente a pedidos anteriores já concluídos", confere que o método da consulta é do tipo GET. Sempre que você acessar o pedido no backoffice, os dados entregues nesse GET são informados nessa área:

Exemplo
![Screenshot at 2020-12-09 16-39-48](https://user-images.githubusercontent.com/7054224/101679858-a83ebf80-3a3e-11eb-8c15-e032b5946371.png)

Atenciosamente,
Equipe PrestaBR
