### ISSUE TITLE
Erro somente por boleto (dados ausentes no cadastro do cliente na loja)

### ISSUE THREAD

**Issue by fchiqueto** [pagseguro/pagseguro-modulo-prestashop#118]
Olá @prestabr 

Estou com um erro somente se opta por pagamento via boleto, na resposta da API aparece isso:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<errors>
  <error>
    <code>53018</code>
    <message>sender area code is required.</message>
  </error>
  <error>
    <code>53118</code>
    <message>sender cpf or sender cnpj is required.</message>
  </error>
  <error>
    <code>53021</code>
    <message>sender phone invalid value: 0</message>
  </error>
  <error>
    <code>53111</code>
    <message>eft bank is not accepted.</message>
  </error>
  <error>
    <code>53118</code>
    <message>sender cpf or sender cnpj is required.</message>
  </error>
</errors>`

Já vi todas Issues aqui e passei horas tentando resolver sem sucesso.

**Comment by prestabr** [comment]
Bom Dia fchiqueto,

Agradecemos por utilizar o módulo oficial em sua loja! :)

Obrigado também por postar o registro do log, facilita para conserguirmos te ajudar.

```
<?xml version="1.0" encoding="UTF-8"?>
<errors>
   <error>
      <code>53018</code>
      <message>sender area code is required.</message>
   </error>
   <error>
      <code>53118</code>
      <message>sender cpf or sender cnpj is required.</message>
   </error>
   <error>
      <code>53021</code>
      <message>sender phone invalid value: 0</message>
   </error>
</errors>
```

Basicamente, o log indica que a sua loja não trata/captura os dados pessoais do cliente durante o cadastro na loja virtual (cpf, telefone, etc).

Na tela de checkout, na modalidade de cartão de crédito, o módulo disponibiliza a opção para o cliente confirmar os dados do titular do cartão (botão:  "Confirmar endereço do titular"), caso não exista nada ele pode preencher na hora, para então mandar processar o pagamento.

Na modalide de boleto bancário não existe essa opção de confirmação e o módulo busca os dados do cliente no cadastro que foi realizado na loja.

Na versão mais recente do módulo disponibilizamos um tutorial rápido para validar e orientar sobre essas questões de cadastro:

PS 1.6, atual v.1.3.0, changelog: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#changelog

PS 1.7, atual v.1.2.0, changelog: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#changelog

Para atualizar o módulo é só seguir o passo-a-passo: https://github.com/pagseguro/pagseguro-modulo-prestashop

Depois de atualizar limpe o cache na tab "Parâmetros Avançados > Desempenho", no canto superior direito "Limpar Cache".

Atenciosamente,
Equipe PrestaBR

**Comment by fchiqueto** [comment]
Certo, já estou usando a versão 1.2.0 PS 1.7.6.8

![ss](https://user-images.githubusercontent.com/17584080/103111503-9ce9b780-462c-11eb-81c3-7a9f407f8ec4.jpg)
![ss2](https://user-images.githubusercontent.com/17584080/103111504-9e1ae480-462c-11eb-96b7-76a673419b2c.jpg)
![ss3](https://user-images.githubusercontent.com/17584080/103111505-9e1ae480-462c-11eb-8028-e40aee56979a.jpg)


Vou reinstalar para ver se o erro continua

**Comment by prestabr** [comment]
Boa Tarde fchiqueto,

> Certo, já estou usando a versão 1.2.0 PS 1.7.6.8

Ótimo, obrigado por confirmar!

> 
> ![ss](https://user-images.githubusercontent.com/17584080/103111503-9ce9b780-462c-11eb-81c3-7a9f407f8ec4.jpg)
> ![ss2](https://user-images.githubusercontent.com/17584080/103111504-9e1ae480-462c-11eb-96b7-76a673419b2c.jpg)
> ![ss3](https://user-images.githubusercontent.com/17584080/103111505-9e1ae480-462c-11eb-8028-e40aee56979a.jpg)
> 
> Neste campos acredito que esteja errada as informações:
> "paymentMethod": "eft",
> "bankName": false,

Este trecho de log é referente a transação via Transferência e não Boleto. O campo "bankName" recebe o nome do banco que foi selecionado na tela de checkout.

> 
> Nestes está vazio porém o endereço ele captura corretamente
> 
> "senderCPF": "",
> "senderAreaCode": "",
> "senderPhone": false,
> "senderHash": false,

Exemplo de captura correta:

"senderCPF": "08944971200",
"senderAreaCode": "11",
"senderPhone": "4003-1775",
"senderHash": "6693912ae157d2b96916cc0d80e421978d13dcf92a2bf986f38da651d898b1be"

Esses campos são obrigatórios, sendo o "senderHash" gerado automaticamente e internamente no módulo ao carregar a tela de checkout, para iniciar o processo de pagamento.

> 
> E também ele carrega na pagina de checkout estes dados no formulário
> 
> Vou reinstalar para ver se o erro continua

Recomendamos que, se possível, tente fazer novos testes em uma loja PrestaShop 1.7 sem customizações e ou alterações de Core ou Overrides. Verifique se as permissões da hospedagem estão corretas: 644 para arquivos e 755 para diretórios. Tente utilizar um módulo para customizar o cadastro do cliente, existem várias opções da internet pesquisando pelo termo "padrão de cadastro brasileiro prestashop".

Na primeira quinzena de Janeiro estaremos lançando uma nova update com correções de bug, atualizações e remoção do hsbc na opção de Transferência.

Atenciosamente,
Equipe PrestaBR

**Comment by fchiqueto** [comment]
@prestabr hoje que consegui testar e foi resolvido desinstalando limpando no DB e instalando novamente.

Acredito que por ter instalado o Modulo de cadastro depois do pagseguro ocorreu esse erro, mesmo instalando novamente deu o erro somente depois de realmente desinstalar por completo resolveu.

Obrigado!

**Comment by prestabr** [comment]
Boa Noite fchiqueto,

Ótimo, agradecemos o seu feedback!

É sempre bom limpar o cache da loja quando instalar ou desinstalar um módulo, verificar as permissões do host também, isso evita muitos contratempos.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
