### ISSUE TITLE
Erro na apresentação das parcelas (módulo desatualizado na loja)

### ISSUE THREAD

**Issue by HomeroOttoniJr** [pagseguro/pagseguro-modulo-prestashop#119]
Estou com um problema estranho, ao apresentar as parcelas no checkout do PagSeguro, na loja Presta Shop 1.7, até um determinado valor todas são exibidas corretamente, da opção 1 parcela (sem juros), até a opção em 12 parcelas, com juros.

Mas conforme o valor aumenta, as parcelas vão desaparecendo. Se o valor do produto passar de 10 mil, nenhuma parcela é exibida.

O suporte do PagSeguro, que desenvolveu o módulo, diz que não encontra nada errado (nem procuraram me parece) e que eu tenho que "falar com o Presta Shop".  Mas não imagino como o Presta Shop poderia corrigir um módulo de terceiros.

Enfim, se alguém já teve um problema semelhante, ou tem alguma sugestão eu agradeço muito.

3 imagens dos parcelamentos.

![image](https://user-images.githubusercontent.com/76544731/103057976-baad1300-457f-11eb-98ab-d5c271e874ca.png)

![image](https://user-images.githubusercontent.com/76544731/103057993-c4cf1180-457f-11eb-9e16-ca34035fbfab.png)

![image](https://user-images.githubusercontent.com/76544731/103057947-ab2dca00-457f-11eb-9561-132304651935.png)

**Comment by prestabr** [comment]
Bom Dia HomeroOttoniJr,

Agradecemos por utilizar o módulo oficial em sua loja! :)

Obrigado também por detalhar o problema enfrentado.

Por favor, confere este post a respeito do bug: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/113#issuecomment-682598963

Basicamente você precisa atualizar o módulo em sua loja, na PS 1.7 a versão mais recente do módulo é a v.1.2.0 (atualizado em 24 de Outubro), changelog (changelog = informativo sobre a atualização): https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#changelog

Para atualizar o módulo é só seguir o passo-a-passo de instalação, o processo é o mesmo: https://github.com/pagseguro/pagseguro-modulo-prestashop

Depois de atualizar limpe o cache na tab "Parâmetros Avançados > Desempenho", no canto superior direito "Limpar Cache".

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR

**Comment by HomeroOttoniJr** [comment]
Olá
Muito obrigado pela ajuda. Eu fiz o procedimento para atualizar a versão, exclui a anterior e instalei a nova.

Parece estar tudo certo, mas a opção de pagamento pelo PagSeguro não aparece no checkout. Tem algo a mais que eu deva configurar para exibir novamente o PagSeguro?

Já limpei o cache mas não resolveu.

Um abraço.

**Comment by prestabr** [comment]
Oi HomeroOttoniJr,

Ótimo, obrigado pelo feedback!

Por favor, confere essa dica: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/79

Utilizando a PrestaShop 1.7, acesse no Back Office a tab "Pagamento > Preferências > Restrições de transportadora" e verifique se as transportadoras estão vinculadas à forma de pagamento.

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR

**Comment by HomeroOttoniJr** [comment]
Olá

Ótimo, muito obrigado, era apenas isso, e agora tudo funciona corretamente, inclusive as parcelas para produtos de qualquer valor!

Um abraço e muito obrigado mais uma vez.

Homero

**Comment by prestabr** [comment]
Olá HomeroOttoniJr,

Perfeito! Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
