### ISSUE TITLE
Problema ao alterar Status (loja com cache travado)

### ISSUE THREAD

**Issue by Luan1Schons** [pagseguro/pagseguro-modulo-prestashop#120]
Oi presta!!! Estou com estes problemas quando realizo um pagamento e vou verificar os logs não sei oque poderia acarretar nestes problemas
poderia me ajudar porfavor?
https://prnt.sc/wib6da

**Comment by prestabr** [comment]
Boa Tarde Luan1Schons,

Obrigado por utilizar o módulo oficial em sua loja! :)

Este erro com o método insert indica que o módulo não conseguiu salvar a troca de status durante a criação do pedido.

![download](https://user-images.githubusercontent.com/7054224/103926165-5483cc80-50f7-11eb-8e08-857a821f99cd.png)


A atualização de status é automatizada, acessa as configurações do módulo e verifica se o mapeamento de status está configurado corretamente: 

PS 1.6: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#3---status-de-pedido

PS 1.7: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#3---status-de-pedido

Os status disponibilizados no mapeamento são os cadastrados na tab "Compras ou Pedidos > Status".

Dica:

Se puder, verifique também as permissões em sua hospedagem, o ideal é 644 para arquivos e 755 para diretórios.

Matenha o módulo sempre atualizado, a versão mais recente pra PS 1.6 é a v.1.3.0 e pra PS 1.7 é a v.1.2.0.

Para atualizar o módulo é só seguir o passo-a-passo: https://github.com/pagseguro/pagseguro-modulo-prestashop

Depois de atualizar limpe o cache na tab "Parâmetros Avançados > Desempenho", no canto superior direito "Limpar Cache".

Atenciosamente,
Equipe PrestaBR

**Comment by Luan1Schons** [comment]
Oii Presta, Obrigado pela resposta, o estranho é que todos os status que estão configurados no módulo já aparecem em opções de pedidos -> status, oque poderia ser?

**Comment by Luan1Schons** [comment]
Algum status padrão esta vindo vazio, porém não consigo identificar qual é.
Todos estão setados na configuração do módulo

print: https://prnt.sc/wiyhiw

**Comment by prestabr** [comment]
Boa Tarde Luan,

Se você tiver status duplicados cadastrados de outras soluções já instaladas pode ser que eles estejam desativados, se o módulo capturar esses status desativados temos a origem do problema. Lembrando que o módulo não instala status, ele apenas utiliza e captura os já existentes.

Existindo status duplicados, tenta mapear outros e faz um teste de compra para ver se foi possível utilizar o status.

Se não conseguir resolver manda pra gente o acesso ao seu painel de controle da loja que verificamos pra você: sac@prestabr.com.br.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Noite Luan,

Obrigado pelos dados de acesso. Agradecemos o seu feedback por email e desejamos Boas Vendas! :)

![Screenshot at 2021-01-11 19-22-23](https://user-images.githubusercontent.com/7054224/104245331-d438d080-5442-11eb-97f9-8f6b09c4fddc.png)

Atenciosamente,
Equipe PrestaBR

**Comment by Luan1Schons** [comment]
Obrigado, meu problema foi corrigido!!!
