### ISSUE TITLE
Modulo pagseguro sem retorno (problemas na configuração da hospedagem [compartilhada])

### ISSUE THREAD

**Issue by will623** [pagseguro/pagseguro-modulo-prestashop#121]
Olá!

Sou iniciante na área de TI e fui solicitado a produzir um e-commerce e me indicaram o Prestashop. Conheci a ferramenta, consegui reproduzir o site da forma como o cliente queria mas me deparei com um problema do qual estou a meses tentando resolver e não consigo. 

Instalei o modulo do Pagseguro compatível com a versão do Prestashop1.7.6.7. A instalação foi bem concluída, todos os parâmetro atendidos e requisitados foram preenchidos sem que houvesse falha. Mesmo assim, quando coloquei o cartão teste do Pagseguro o Prestashop carrega por um determinado tempo a finalização da compra mas me retorna um erro de validação. Já procurei respostas em fóruns, site, blogs mais todas as ações que foram recomendadas não serviram para o meu problema. Gostaria de uma ajuda para resolver esse problema, onde realmente posso mexer, se isso tem algo haver com o htacess ou se é alguma configuração do Prestashop na qual eu não ajustei. 

Abaixo, colocarei a tela de erro que aparece após 60 segundos da tentativa de finalização da compra.
!
![image thumb png 7c28fcd0137ef7cfaa327232bdcc183e](https://user-images.githubusercontent.com/59579781/104601654-3e2ac300-5659-11eb-9d10-699d1518e624.png)

**Comment by prestabr** [comment]
Boa Tarde will623,

Obrigado por escolher o PagSeguro para a sua loja! :)

Muitos problemas de funcionamento na loja ou em módulos tem origem na configuração da hospedagem. Para a plataforma PrestaShop o ideal é utilizar uma hospedagem mais robusta do tipo VPS, que já conta com uma configuração mais detalhada. Hospedagens do tipo Compartilhada geralmente são recomendadas para softwares menos complexos, como sites e landingpages que não exigem diversos recursos e processamento de dados.

Aparentemente, este erro do print indica dificuldade para inserir os dados do pedido no banco de dados. Faça alguns testes:

- Confere se as permissões dos arquivos e diretórios estão configuradas corretamente na hospedagem: 644 para arquivos e 755 para diretórios;

- O módulo possuí 02 tabelas no banco de dados, verifique se a integridade delas estão ok comparando com este arquivo:
https://github.com/pagseguro/pagseguro-modulo-prestashop/blob/master/1.7.x/checkout-transparente/pagseguropro/sql/install.php

- O módulo em modo de produção com a loja em modo debug acaba gerando problemas. O debug pode limitar a coleta de dados e redirecionamentos para a conclusão do pedido. O ideal é processar o pagamento com o debug desligado, tab "Parâmetros Avançados > Desempenho" na opção "Modo de Depuração".

- Verifique se a hospedagem consegue gerar o SessionID desta forma:

https://www.minhaloja.com.br/modules/pagseguropro/update.php?acao=session

Exemplo de retorno:

![87227154-5ef32280-c36f-11ea-9341-427180019c53](https://user-images.githubusercontent.com/7054224/104617662-7981bd80-566a-11eb-93c8-a3edab76fe6a.png)

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Bom Dia will623,

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR

**Comment by will623** [comment]
Olá! 

Fiz todos os procedimentos mas nenhum solucionou o meu problema.  Ainda estou buscando identificar o erro, e não sei se o que achei tem a ver com esse problema, mas parece que o JavaScript esta tendo conflito. 
![ConsoleError](https://user-images.githubusercontent.com/59579781/106315235-b85a6a80-6249-11eb-95bd-8a35f0a8e2a9.png)

**Comment by prestabr** [comment]
Olá will623,

Só p/ organizar, respondido no issue original https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/123

Atenciosamente,
Equipe PrestaBR
