### ISSUE TITLE
Requisitos

### ISSUE THREAD

**Issue by xworx** [pagseguro/pagseguro-modulo-prestashop#122]
Boa noite

Não localizei os requisitos de sistema para utilização do módulo, podem me ajudar?

Utilizo na minha PS 1.6:

PHP 5.6.40
MySQL 10.3.27-MariaDB

Há alguma incompatibilidade?

Obrigado

**Comment by prestabr** [comment]
Bom Dia xworx,

Os requisitos de compatibilidade são mínimos, estão disponíveis na documentação do módulo, confere:

PS 1.6
https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#compatibilidade

PS 1.7
https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#compatibilidade

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR
