### ISSUE TITLE
Erro no JavaScript

### ISSUE THREAD

**Issue by will623** [pagseguro/pagseguro-modulo-prestashop#123]
Olá PrestaBR! 

Estou com um problema referente ao pagseguro que não está me retornando a confirmação de pagamento após finalizar a compra. Tenho buscado identificar o problema e me deparei com um conflito no JavaScript, ao olhar se alguns elementos estavam aparecendo e não obtive sucesso, Gostaria de um suporte para identificar o problema e como soluciona-lô. 

![ConsoleError](https://user-images.githubusercontent.com/59579781/106313897-b55e7a80-6247-11eb-9f99-099cd729f1d6.png)

**Comment by prestabr** [comment]
Boa Tarde will623,

Esses erros no console do seu navegador indicam que existem alguns conflitos em scritps do tema (layout), módulos de terceiro ou scripts externos inseridos diretamente no tema.

Imagina que o JavaScript funciona dessa forma:

Processo A - arquivos .js do tema
Processo B - arquivos .js externos
Processo C - arquivos .js do módulo pagseguropro

Se algum conflito existir no processo A ou B o processo C não vai funcionar direito e vai apresentar problema.

Clica na linha de erro "custom.js 8" e verifica a origem do erro, tenta remover o script, corrigir o erro ou desativar o módulo se for o caso, o mesmo vale para o chat da tolvnow.

Consertanto esses 2 pontos você deve conseguir fazer o módulo de pagamento funcionar bem. Para verificar se está funcional, confere: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde will623,

Encerrando a issue, qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR
