### ISSUE TITLE
Erro ao finalizar pagamento - sender is blocked.

### ISSUE THREAD

**Issue by rafaelsilvabra** [pagseguro/pagseguro-modulo-prestashop#124]
Olá amigos.

Eu atualizei o módulo porque achei q esse era o problema mas infelizmente não. Ao tentar finalizar a compra com cartão ou boleto, aparece para o cliente o modal informando que não pode gerar o pedido e no dashboard do presta eu peguei o seguinte erro.

Podem ajudar? Foi de 2 dias para cá o problema.
Confirmei o token do pagseguro e está ok.

![image](https://user-images.githubusercontent.com/31866021/116606533-3ee51d80-a907-11eb-8e69-9da002b19522.png)

**Comment by prestabr** [comment]
Boa Tarde rafaelsilvabra,

Erro código 53141 "sender is blocked", indica que o cliente tem alguma restrição na conta dele no PagSeguro e por este motivo não é possível processar o pagamento. Este bloqueio pode ser por fraude, saldo negativo, documentação pendente, má fé em disputas com outras compras, etc. 

Para resolver o cliente precisa entrar em contato com o PagSeguro para resolver as pendências na conta dele ou tentar comprar na loja com outro cpf/email de cadastro.

Qualquer dúvida fique à vontade para perguntar.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Obrigado por responder amigos.

Eu fiz um cadastro em nome da esposa e deu certo todo o processo.
Única coisa que achei estranho é essa informação no topo do site. Como remover?
Obrigado.
![image](https://user-images.githubusercontent.com/31866021/116699877-7ce05100-a99c-11eb-9c11-c6e7c81e0453.png)

**Comment by prestabr** [comment]
Boa Tarde rafaelsilvabra,

Ótimo, agradecemos o seu feedback!

Essa informação no topo do site não é do módulo de pagamento do PagSeguro. Confere se a loja está usando algum script na página de confirmação, se tem alguma coisa configurada direto no layout, se algum módulo antigo deixou um hook configurado nessa área ou até se o debug da loja está ativo.

Atenciosamente,
Equipe PrestaBR
