### ISSUE TITLE
PIX

### ISSUE THREAD

**Issue by rafachiarello** [pagseguro/pagseguro-modulo-prestashop#126]
Prezados,
A PagSeguro já está disponibilizando aos usuários os recebimentos por PIX, nos estabelecimentos comerciais que possuem as maquinas de cartão.
Pergunto se existe qualquer perspectiva desta nova modalidade de pagamentos ser disponibilizada também aos usuários que possuem integração com ecommerce, em especial nós da prestashop?

Aproveito para cumprimentá-los e agradecer pelo excelente serviço prestado no desenvolvimento, manutenção e suporte deste módulo imprescindível para o nosso trabalho!

Cordialmente, Rafael

**Comment by prestabr** [comment]
Bom Dia rafachiarello,

Agradecemos o seu feedback! :)

O módulo utiliza a Api v3 de Checkout Transparente e nesta modalidade não existe o Pix. 

Em breve o PagSeguro irá lançar a Api v4 de Checkout Transparente, que será muito mais moderna, rápida e segura. Nesta nova Api estará disponível Cartão de Crédito (+30 bandeiras aceitas), Boleto e Pix.

Por enquanto a Api v4 ainda é versão beta e não tem data definida para o lançamento, mas será em breve e já estamos trabalhando em um novo módulo totalmente reformulado e aprimorado.

Vamos deixar essa issue fixada e assim que tivermos uma data em mãos voltamos aqui para informar.

Atenciosamente,
Equipe PrestaBR

**Comment by rafachiarello** [comment]
Olá, equipe!
Muito obrigado pelo breve retorno e as informações prestadas!

Acredito que a referida nova versão da API Checkout Transparente deverá evoluir e ficar muito melhor, além de oportunizar melhores formas de recebimentos aos usuários. Estarei esperando ansiosamente pelo seu lançamento!

À vocês, votos de um ótimo trabalho e sucesso total no desenvolvimento do novo módulo!

Cordialmente, Rafael

**Comment by velys** [comment]
Alguma previsão para o PIX no prestashop?
pois esse post é de 2021

**Comment by prestabr** [comment]
Boa Tarde velys,

Agraecemos o seu contato/interesse!

Houve atrasos no lançamento da nova API e tivemos que prorrogar bastante o prazo.

A nova API já está disponível e já estamos trabalhando na nova solução para a PrestaShop, a previsão é lançar agora em Abril. O módulo será bem flexível e compatível com a PrestaShop 1.6.x, 1.7.x e 8.0.x, do PHP 5.6 ao 8.x, oferecendo pagamentos via Cartão de Crédito, Boleto e Pix, entre outras funcionalidades.

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR
