### ISSUE TITLE
Unknown web session id (Problema de permissão nos arquivos e diretórios na hospedagem)

### ISSUE THREAD

**Issue by lukidj** [pagseguro/pagseguro-modulo-prestashop#127]
Olá, instalei o modulo em minha loja mas fica dando Unknown web session id

**Comment by lukidj** [comment]
Ja tentei varios  modelos aqui mas não funciona e quero muito usar a pag seguro

**Comment by prestabr** [comment]
Boa Noite lukidj,

Seja muito-bem vindo e obrigado por utilizar o módulo oficial do PagSeguro!

Vamos te ajudar a resolver essa questão, por favor, faça alguns testes:

a) Verifique se o token é de produção e o ambiente também;
https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#1---ativa%C3%A7%C3%A3o

b) Um problema bastante comum são as permissões erradas nos arquivos e pastas na sua hospedagem: /public_html/modules/pagseguropro/, o ideal é 755 para pastas e 644 para arquivos;

c) Verifique se a hospedagem está ok tentando gerar o SessionID desta forma:

https://www.minhaloja.com.br/modules/pagseguropro/update.php?acao=session

Exemplo de retorno:

![87227154-5ef32280-c36f-11ea-9341-427180019c53](https://user-images.githubusercontent.com/7054224/135189692-5ed6bc0b-3784-470c-a297-cc751d1ca609.png)

Aguardamos seu retorno.

Atenciosamente,
Equipe PrestaBR

**Comment by lukidj** [comment]
Quando acesso esse link vai para um pagina de erro 404 do meu site https://.www.........com.br/modules/pagseguropro/update.php?acao=session

E ja verifiquei tudo alem disso ate olhei os outros passos e tudo ta ok, mas n entendo que ainda da o mesmo erro.

Me ajudem

**Comment by prestabr** [comment]
Boa Tarde lukidj,

O erro "Unknown web session id" indica que o módulo não conseguiu iniciar a sessão de pagamento junto ao PagSeguro. Essa dificuldade é originada pelo servidor de hospedagem, motivos comuns:

- Permissões erradas nos diretórios;
- Hospedagem compartilhada, lenta ou com limitações de configurações e/ou conectividade;

> Quando acesso esse link vai para um pagina de erro 404 do meu site https://.www.........com.br/modules/pagseguropro/update.php?acao=session

Para a plataforma PrestaShop o ideal seria utilizar uma hospedagem do tipo VPS. Hospedagens do tipo Compartilhada geralmente são recomendadas para softwares menos complexos, como sites e landingpages que não exigem diversos recursos e processamento de dados.

Nossa recomendação é que você tente migrar a sua loja para outra hospedagem e depois refaça os testes.

Atenciosamente,
Equipe PrestaBR

**Comment by lukidj** [comment]
Sim SIm eu entendo, mas não estou hospedado em compartilhada,  é uma vps

aaah so quero essa plataforma q dificil

**Comment by prestabr** [comment]
Boa Tarde lukidj,

Se você já está em uma VPS então deve ter algum problema de configuração que vocês está deixando passar batido.

Manda pra gente o endereço da sua loja + acesso ao admin + acesso ao FTP da sua hospedagem, vamos analisar o problema pra você e retornamos em até 48hs. Email: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde lukidj,

Conforme nos falamos por email o problema eram as permissões dos arquivos e diretórios. O módulo está funcionando corretamente e está ativo no checkout da sua loja, você pode deixar ele funcionando em conjunto com qualquer outro módulo de pagamento. Basta ativar ou desativar o(s) módulo(s), fica à seu critério.

Vale sinalizar que o padrão (755 para diretórios e 644 para arquivos) de permissões na hospedagem é requisito básico de configuração da Plataforma PrestaShop (todos os arquivos do sistema, tudo em sua /public_html/, sem exceções), isso evita mau funcionamento de áreas diversas do sistema, aumenta a segurança da sua loja, etc. Quando puder, não deixe entrar em contato com o suporte técnico da sua hospedagem e peça para lançarem os ajustes para você.

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR
