### ISSUE TITLE
PagSeguro + Prestashop 1.7.7.5

### ISSUE THREAD

**Issue by cunha-fabricio** [pagseguro/pagseguro-modulo-prestashop#129]
Olá, 

Consegui instalar e fazer vendas de teste no módulo, porem no backoffice quando na tela do pedido, mostra algumas informações antes e depois do botão de cancelar a transação que acredito nao precisam estar ali.

Poderia me orientar nessa correção? Obrigado

![Captura de Tela 2021-10-21 às 15 23 58](https://user-images.githubusercontent.com/58490559/138335984-dba43a18-8027-47d3-bcf0-d5ee41110950.png)
![Captura de Tela 2021-10-21 às 15 23 46](https://user-images.githubusercontent.com/58490559/138335989-16d88fff-5f7d-45c2-b720-60ed7e1a1b7e.png)

**Comment by prestabr** [comment]
Boa Tarde cunha-fabricio,

Agradecemos o seu contato! :)

Este ajuste é relacionado à layout e compatibilidade com o novo bootstrap nas versões mais recentes no admin da loja. Não prejudica o funcionamento da loja/pedidos e já está agendado para a próxima update. Estaremos lançando até sábado agora dia 23/10, versão 1.3.1.

Confere por favor: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/128#issuecomment-944019833

Atenciosamente,
Equipe PrestaBR
