### ISSUE TITLE
Versão PHP 7.4 para Prestashop 1.7.8X

### ISSUE THREAD

**Issue by rafachiarello** [pagseguro/pagseguro-modulo-prestashop#130]
Olá!
Estou em vias de atualizar minha Prestashop para a versão mais recente e inclusive a versão PHP para a 7.4, a qual já é suportada pela nova versão da PRESTA.
Pergunto se o módulo PagSeguro também está compatível com esta versão PHP.

Obs. Notei que o assunto foi abordado na issue #128 , porém não especificamente para esta versão PHP: 
"É compatível, já testamos na PS 1.7.8.0 (lançada agora em 07/10/21) com PHP 7.3.31."

No aguardo, grato desde já!

**Comment by prestabr** [comment]
Boa Tarde rafachiarello,

Também é compatível, testamos novamente na PS 1.7.8.0 e agora com o PHP 7.4.25.

Desejamos Boas Vendas! :)

Qualquer dúvida ou problema estamos à disposição.

Atenciosamente,
Equipe PrestaBR
