### ISSUE TITLE
Api v4 Sugestões

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/pagseguro-modulo-prestashop#131]
Olá meus amigos, 
Estou sabendo que em breve vocês lançarão a V4 do referido módulo. 
Eu gostaria de fornecer algumas sugestões. 
Além de tudo que já tem e que vocês irão fazer:

- Garantir que os campos onde serão inseridos números (CPF, Telefone, Dada de Nascimento, CNPJ etc) tenham as devidas máscaras. 
- Altear o tipo de teclado para campos numéricos para acessos feitos por smartphone (por exemplo, ao digitar o número do cartão, seria interessante todo o telcado do smartphone conter apenas números, como se fosse fazer uma chamada de telefone). Assim fica mais fácil, prático e fluído fazer tal operação. 
- Dar uma atenção super especial ao acesso via smartphone. Não só em meu site, mas em todo o globo, mais de 80% dos acessos na web são feitos via aparelhos móveis. Por favor, dêem uma atenção maior para a responsibilidade. Eu uso o módulo de vocês há muitos anos e toda a vez que eu atualizo tenho que entrar na programação e mudar vários parâmetros para deixar o módulo de vocês responsivo em meu site. Segue um exemplo de como o módulo de vocês fica quando eu instalo ou atualizo: [
![cartaoantes](https://user-images.githubusercontent.com/56834125/140936169-dca6e2c1-216f-495c-bc03-d2446c4be4b3.JPG)
](url)
![boletoantes](https://user-images.githubusercontent.com/56834125/140936223-2859b561-6455-4c8b-8c80-c6bc264dd71d.JPG)
Agora olha como fica quando eu mudo os parâmetros na programação: 
![cartaodepois](https://user-images.githubusercontent.com/56834125/140936844-f3542428-cb96-4898-81a0-e6d2bf98b877.JPG)
![boletodepois](https://user-images.githubusercontent.com/56834125/140936316-cb34bcf8-68ae-4b75-8dbc-c3cd4670b7aa.JPG)
Em fim, segue aí minhas considerações. 
Obrigado pelo excelente trabalho. 
At, Glauco

**Comment by prestabr** [comment]
Boa Tarde Glauco,

Agradecemos o seu feedback! :)

Todos os ajustes que você listou são considerados fundamentais e já constam nos módulos desde a primeira versão (lançamento). Os módulos trabalham seguindo estritamente as boas práticas de desenvolvimento da plataforma e são desenvolvidos em cima do layout (tema) padrão da PrestaShop.

A dificuldade da sua loja para carregar a máscara e teclado numérico nos inputs (cpf, telefone, número do cartão, etc), além do mais importante e básico que é o layout responsivo pro Mobile, deve ser por conta de algum conflito de JavaScript e/ou alguma customização de css/bootstrap e estruturas gerais do seu tema, isso é bem comum em layout comprados prontos (o padrão de qualidade costuma variar bastante).

Você pode tentar instalar os módulos em uma loja padrão para conferir estes detalhes, exemplo:

PS 1.6
![ps16](https://user-images.githubusercontent.com/7054224/140965402-769e21e3-7ad9-42a5-9987-9bbab9e20efe.jpg)

PS 1.7
![ps17](https://user-images.githubusercontent.com/7054224/140965413-9abe6661-9f2e-42c7-b453-576e1d2eb2c9.jpg)

Para você não ter que ajustar os layouts para as particularidades do seu tema toda vez que sair uma update é só trabalhar com overrides. https://devdocs.prestashop.com/1.7/themes/reference/overriding-modules/ (essa doc também serve p/ 1.6)

Desejamos Boas Vendas!!

Atenciosamente,
Equipe PrestaBR
