### ISSUE TITLE
Problema na finalização do pedido com pagamento por Cartão de Crédito (não preencheu todos os campos na tela de pgto)

### ISSUE THREAD

**Issue by rafachiarello** [pagseguro/pagseguro-modulo-prestashop#132]
olá!
Recentemente (16/11/21) realizei a última atualização do módulo em minha plataforma.
Ocorre que hoje verifiquei que, após esta atualização, há um problema na finalização do pedido com pagamentos por cartão de crédito.
Basicamente, após o preenchimento de todos os campos, o botão "PAGAR E FINALIZAR PEDIDO" simplesmente não funciona, sem aparecer nenhuma mensagem de erro, apenas o símbolo do bloqueio no cursor do mouse. (VER ANEXO)
Verifiquei os logs e não encontrei nenhum registo de falha.

Diante disso, venho pedir auxílio de vcs para tentar entender e resolver o referido problema.
![Módulo PagSeguro - erro finalização cartão de crédito](https://user-images.githubusercontent.com/60196289/143256608-559428dc-3037-40d8-9d44-4b2796222cb8.jpg)

**Comment by prestabr** [comment]
Boa Tarde rafachiarello,

Geralmente travamentos ou congelamentos são ocasionados por conflitos de JavaScript. Para agilizar o seu atendimento, fizemos um cadastro em sua loja para visualizar e tentar entender melhor o problema, mas não divemos dificuldades para mandar processar o pagamento no cartão.

![Screenshot at 2021-11-24 12-19-36](https://user-images.githubusercontent.com/7054224/143266437-6fdc957b-37a3-418c-96c5-18b0f1f92082.png)

Sempre que você atualizar algum módulo em sua loja é importante limpar o cache na tab "Parâmetros Avançados > Desempenho".

Para verificar se o módulo está funcional em sua loja utilize o Debug: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.7.x/checkout-transparente/pagseguropro#6---debug-para-solu%C3%A7oes-de-problemas

Atenciosamente,
Equipe PrestaBR

**Comment by rafachiarello** [comment]
Pessoal, boa tarde!
Muito obrigado pelo breve retorno!
Ao analisar melhor a situação, eu verifiquei que não havia preenchido o campo destinado ao código verificação do cartão.
Estou com 1 cliente que não está conseguindo finalizar uma compra, dá apenas "pagamento não autorizado", e no anseio de tentar entender e resolver logo o problema acabei cometendo essa gafe.

Mas a propósito, seria interessante que fosse indicado na tela esta falta de preenchimento de campos, pois assim, no ato, seria possível saber imediatamente o problema que impede a finalização da compra.
Simplesmente haver um bloqueio do botão de finalização não ajuda em nada....

Muito obrigado!

**Comment by prestabr** [comment]
Olá rafachiarello,

Agradecemos o seu feedback! Vamos levar em consideração para eventuais melhorias na próxima update..!

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
