### ISSUE TITLE
Erro ao finalizar compra

### ISSUE THREAD

**Issue by WebGF** [pagseguro/pagseguro-modulo-prestashop#133]
![Capturar01](https://user-images.githubusercontent.com/56832697/165148271-a9a0ac14-f936-4115-a480-b2cc48a8068c.PNG)
![Capturar02](https://user-images.githubusercontent.com/56832697/165148278-a3dc8647-8eb9-43ea-8e91-5989f1be041e.PNG)
Não tenho certeza do que esta acontecendo. Instalei a ultima versão do pagseguro.
Chego na pagina de pagamento e quando fiz uma compra teste pagando com o boleto bancario dispara esses erro ao clicar no botão.
PRestashop 1.6

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Desativa o debug da sua loja em /config/defines.inc.php:

/* Debug only */
if (!defined('_PS_MODE_DEV_')) {
define('_PS_MODE_DEV_', **false**);
}

O módulo em modo de produção com a loja em modo debug acaba gerando problemas. O debug pode limitar a coleta de dados e redirecionamentos. Basicamente o boleto executa um redirect no validation pra processar o inset e posterior tela de confirmação de pedido.

Mesma questão... https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/107#issuecomment-658207731

Qualquer dúvida ou problema fique à vontade para perguntar, estamos à disposição.

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
Muito obrigado! 
Agora esta funcionando direitinho.
Att. Mauricio
