### ISSUE TITLE
Pagamento Não Avança Sem Data de Nascimento (feedback otimizações)

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/pagseguro-modulo-prestashop#135]
Olá amigos, bom dia. Estou voltando aqui depois de 4 anos sem nenhum problema. Parabéns a toda equipe e trabalho. 

Eu estou tendo alguns incovenientes com alguns clientes que questionam que não conseguem finalizar a compra porque quando clicam no botão para finalizar, não avança (fica parado). Eu descobri que 99,9999% desses casos estão relacionados com a data de nascimento que não foi preenchida. 

Acontece que, se todos os campos estiverem preenchidos, menos a data de nascimento, o botão para finalizar não fica disponível, mas os clientes clicam nele e acreditam que algo vai acontecer - e realmente não acontece nada (afinal de contas, ele está indisponível ainda). Daí esses clientes 1) desistem ou 2) pagam com o mercado pago ou 3) reclamam.  Dos clientes que reclamam, nos informamos que o botão para finalizar só fica disponível se a data de nascimento estiver preenchida - e dá certo!

Venho apenas sugerir que quando o cliente tentar clicar no botão para finalizar compra, e algum campo obrigatório, estiver em branco, que apareça apenas uma mensagem dizendo que ele precisa preencher todos os campos antes de finalizar. Daí o cliente vai revisitar os campos e verá que faltou a tal da data de nascimento ou algum outro dado obrigatório. O módulo só informa que o campo obrigatório está preenchido errado, mas ele não informa que está faltando "o dado", porque o botão para finalizar não fica disponível.

Hoje em meu site é assim: cliente aciona o suporte informando que clica para pagar e não avança, a gente já informa que está faltando a data de nascimento - e problema é resolvido.  

Por favor, me perdõe pela delonga, eu sou muito inseguro nas palavras e escrevo muito para ter certeza de que vocês entenderam a situação. De qualquer forma, estou disponível para mais esclarecimentos. 

Reforço meu apreço pelo trabalho de todos vocês. 

At,

**Comment by prestabr** [comment]
Boa Tarde glaucomodera,

Agradecemos o seu tempo para compartilhar conosco o seu feedback..!

O módulo já realiza a validação da te todos os campos (obrigatoriedade, formatação e se está em branco) em tempo real e após uma ação do cliente (clicar no campo, clicar em pagar, etc).

Na área de checkout, na PrestaShop 1.7, existe a opção de desabilitar o botão padrão de termos de serviço (Parâmetros da loja > Configurações de pedidos > Termos de serviço).
Com essa opção desabilitada a validação dos campos em tempo real desativa o botão de pagar aguardando que o cliente revise os dados. Após o preenchimento o botão é liberado e se o cliente clicar em pagar e ainda houver alguma pendência é exibida uma mensagem com o indicativo.
Com a opção habilitada o botão de pagar só é liberado após o aceite dos termos e caso algo ainda esteja pendente será exibida uma mensagem com o indicativo após clicar em pagar.

Vamos realizar alguns testes e pensar em alguns ajustes para deixar essa validação dos campos mais evidente e intuitiva. Estaremos lançando uma update com essas melhorias no dia 18/11.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde glaucomodera,

Desculpe a demora para retornar o seu contato. Discutindo essa e outras melhorias, optamos por lançar os ajustes para o novo módulo que irá trabalhar com a nova api. Ela é mais rápida e segura e conta com cartão, boleto, pix, pagbank, etc. O lançamento está previsto para o primeiro trimestre de 2023 e será compatível com a PrestaShop 1.6, 1.7 e 8 (que agora está em versão beta).

Atenciosamente,
Equipe PrestaBR
