### ISSUE TITLE
Apoio. Loja não aceita mais pagamento com cartão

### ISSUE THREAD

**Issue by rafaelsilvabra** [pagseguro/pagseguro-modulo-prestashop#136]
Oi amigos,
estou tentando resolver esse problema. 
Estou usando o presta 1.6.1.6 com o módulo 1.4
Após o cliente reclamar atualizei o módulo para 1.6 e o erro persiste.
Se escolher opção boleto funciona mas cartão fica pensando e da erro de transação.

Como posso localizar o possível erro e ver se não é no pagseguro o problema?
Obrigado
![635463546354](https://user-images.githubusercontent.com/31866021/217627308-8bda33f4-3254-46ae-90e8-26a79392b877.png)

**Comment by prestabr** [comment]
Boa Tarde Rafael,

Obrigado pelos detalhes. Com o seu print indicando que o módulo está funcional, sem erros de JavaScript, e com o módulo retornando erro na transação, o ideal é verificar os Logs da comunicação entre a loja e o PagSeguro. Verificando Logs: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/75#issuecomment-567057058

Identificando o Log é só conferir o retorno da API indicando o motivo do erro.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Oi amigos, desculpe a demora.

Eu acabei de realizar um teste com meu cartão.
Eu tenho o erro na tela mas não aparece nada nos logs. Ele não gera nem um pedido para ver o tipo de erro/retorno da api.
![34343434](https://user-images.githubusercontent.com/31866021/219397548-787398fc-8bfe-4760-a25a-bf915c755265.png)

**Comment by rafaelsilvabra** [comment]
Baixei os Logs de erro da loja e vi esse log aqui.
[06-Feb-2023 16:05:15 America/Sao_Paulo] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in modules/pagseguropro/pagseguropro.php on line 2158

Os cartões parou de funcionar depois do dia 2/2.

Boleto é gerado normalmente.

**Comment by prestabr** [comment]
Boa Tarde Rafael,

> Oi amigos, desculpe a demora.
> 
> Eu acabei de realizar um teste com meu cartão. Eu tenho o erro na tela mas não aparece nada nos logs. Ele não gera nem um pedido para ver o tipo de erro/retorno da api. ![34343434](https://user-images.githubusercontent.com/31866021/219397548-787398fc-8bfe-4760-a25a-bf915c755265.png)

Verifica se o gerenciador de Logs está ativo no módulo: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs

O erro do print "Pagamento não autorizado" indica que o pagamento foi negado pelo banco emissor do cartão, o cliente recebe um email do PagSeguro sinalizando que não foi autorizado, não é algo relacionado com problemas de funcionamento no módulo, loja ou hospedagem. Neste caso o ideal é que o cliente entre em contato com o banco para entender melhor o motivo. Em sua conta no PagSeguro é possível veriricar mais detalhes na tab "extrato de transações", pesquisa pelo email ou nome do cliente.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Oi Rafael,

> Baixei os Logs de erro da loja e vi esse log aqui. [06-Feb-2023 16:05:15 America/Sao_Paulo] PHP Warning: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in modules/pagseguropro/pagseguropro.php on line 2158
> 
> Os cartões parou de funcionar depois do dia 2/2.
> 
> Boleto é gerado normalmente.

Aqui do nosso lado no ambiente de testes e homologações não conseguimos reproduzir este erro. Se você atualizou o módulo recentemente ou atualizou a loja/hospedagem confere se os diretórios do módulo estão com as permissões corretas, de forma recursiva 755 pra diretórios e 644 pra arquivos.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
> Boa Tarde Rafael,
> 
> > Oi amigos, desculpe a demora.
> > Eu acabei de realizar um teste com meu cartão. Eu tenho o erro na tela mas não aparece nada nos logs. Ele não gera nem um pedido para ver o tipo de erro/retorno da api. ![34343434](https://user-images.githubusercontent.com/31866021/219397548-787398fc-8bfe-4760-a25a-bf915c755265.png)
> 
> Verifica se o gerenciador de Logs está ativo no módulo: https://github.com/pagseguro/pagseguro-modulo-prestashop/tree/master/1.6.x/checkout-transparente/pagseguropro#7---registro-de-transa%C3%A7%C3%B5es--gerenciamento-de-logs
> 
> O erro do print "Pagamento não autorizado" indica que o pagamento foi negado pelo banco emissor do cartão, o cliente recebe um email do PagSeguro sinalizando que não foi autorizado, não é algo relacionado com problemas de funcionamento no módulo, loja ou hospedagem. Neste caso o ideal é que o cliente entre em contato com o banco para entender melhor o motivo. Em sua conta no PagSeguro é possível veriricar mais detalhes na tab "extrato de transações", pesquisa pelo email ou nome do cliente.
> 
> Obs.: Vale lembrar que você não conseguirá fazer pagamentos para você mesmo caso as credenciais da loja estejam em seu nome no PagSeguro.
> 
> Atenciosamente, Equipe PrestaBR

Sim, está ativo.
![Captura de Tela 2023-02-16 às 12 52 09](https://user-images.githubusercontent.com/31866021/219418181-2ad61b0b-7e03-4827-a193-77076b855a41.png)

**Comment by rafaelsilvabra** [comment]
> Oi Rafael,
> 
> > Baixei os Logs de erro da loja e vi esse log aqui. [06-Feb-2023 16:05:15 America/Sao_Paulo] PHP Warning: simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '<' not found in modules/pagseguropro/pagseguropro.php on line 2158
> > Os cartões parou de funcionar depois do dia 2/2.
> > Boleto é gerado normalmente.
> 
> Aqui do nosso lado no ambiente de testes e homologações não conseguimos reproduzir este erro. Se você atualizou o módulo recentemente ou atualizou a loja/hospedagem confere se os diretórios do módulo estão com as permissões corretas, de forma recursiva 755 pra diretórios e 644 pra arquivos.
> 
> Atenciosamente, Equipe PrestaBR

Sim sim. permissões ok.

Fazer um novo teste com um cadastro 100% novo e ja retorno.
Obrigado

**Comment by rafaelsilvabra** [comment]
Acessei minha conta pagseguro e lá informa que realmente foi cancelada.
Gente, os caras estão com problema lá. Está bloqueando tudo.
A loja não envia pagamento cancelado pro Pagseguro correto? é ele que está bloqueando certo?

![IMG_8510](https://user-images.githubusercontent.com/31866021/219423408-9b13159d-3f62-4d78-80eb-3c7cf4b7d442.PNG)

**Comment by prestabr** [comment]
Olá Rafael,

> Cadastro do zero realizado. Na tela trava com a mensagem q nao pode ser feito o pagamento.
> 
> Nos logs da loja só apareceu esse registro. ![654363546534](https://user-images.githubusercontent.com/31866021/219422201-fcedbe9a-e9f3-4c87-a9ca-1a25256a82d1.jpg)

Perfeito, obrigado pelos detalhes..! O módulo está instalado, configurado, registrando logs e processamento pagamentos, está tudo ok! :)

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá Rafael,

> Acessei minha conta pagseguro e lá informa que realmente foi cancelada. Gente, os caras estão com problema lá. Está bloqueando tudo. A loja não envia pagamento cancelado pro Pagseguro correto? é ele que está bloqueando certo?
> 
> ![IMG_8510](https://user-images.githubusercontent.com/31866021/219423408-9b13159d-3f62-4d78-80eb-3c7cf4b7d442.PNG)

Quem está negando a transação é o banco emissor do cartão, o PagSeguro recebe a negativa do banco e só repassa indicando que não foi atutorizado.

Tenta entrar em contato com banco ou central de cartões, se for algum bloqueio de segurança é só validar as informações e aguardar a liberação, geralmente é feita na hora.

Atenciosamente,
Equipe PrestaBR

**Comment by rafaelsilvabra** [comment]
Então mas de 12 clientes diferentes?
Estou tentando algum suporte do pagseguro pq meu cartão por exemplo é liberado para qualquer site. Tanto que usei ele hoje as 11h normal.

**Comment by prestabr** [comment]
Oi Rafael,

Infelizmente sim, não é algo que temos controle ou que dependa de algum ajuste no módulo. Quem autoriza as transações é o banco emissor do cartão, se ele não autorizar não processa o pagamento. Geralmente está relacionado à questões de segurança por critério do próprio banco. Além do suporte do PagSeguro, tente entrar em contato com o banco pra entender o motivo do bloqueio.

Atenciosamente,
Equipe PrestaBR
