### ISSUE TITLE
Sem o acesso ao login p/ se autenticar e autorizar o App.

### ISSUE THREAD

**Issue by kkadm** [pagseguro/pagseguro-modulo-prestashop#139]
### E-mail de contato

igor@agenciatk.com.br

### O que aconteceu?

Como venho relatando a varias semanas, nao funciona!
![loop](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/130991998/fc44fb76-d7f5-4510-b26b-9ef3ebdcf285)

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.4

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos

**Comment by prestabr** [comment]
Bom Dia kkadm,

Você conseguiu alterar a configuração da parcela sem juros? https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/138#issuecomment-1551734861

Se puder, verifica o log novamente para conferir se é outro problema.

Se mesmo assim não conseguir, por favor, libera um acesso ao ADM da sua loja e encaminha para o email sac@prestabr.com.br que verificamos para você.

Atenciosamente,
Equipe PrestaBR

**Comment by kkadm** [comment]
sim, fiz como foi orientado, inclusive reenviei o arquivo

Em 23/05/2023 09:29, PrestaBR escreveu:

**Comment by prestabr** [comment]
Boa Tarde kkadm,

Se o log que você verificou for realmente este: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/138#issuecomment-1551655927

{
     "error_messages": [
         {
             "error": "max_installments_no_interest_must_not_be_1",
             "description": "Parameter max_installments_no_interest should be equal 0 or greater than 1.",
             "parameter_name": "max_installments_no_interest"
         }
     ]
}

Então é só seguir essa orientação que resolve o problema: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/138#issuecomment-1551734861

Limpa o cache da loja e certifique-se que não existe nenhum tipo de cache de mysql, varnish ou algo do tipo que também precise ser limpo.

Se mesmo assim não resolver, o ideal é dar uma olhada geral nos logs ou conferir se nao é algum problema de JavaScript no checkout.

Em nosso ambiente de testes e homologações, e conferindo algumas lojas que utilizam o módulo em produção, não conseguimos reproduzir e funciona normalmente.

Se puder, por favor, nos envie um acesso ao ADM da sua loja que verificamos ASAP para você, e-mail: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR

**Comment by kkadm** [comment]
Boa noite,

limpei os caches todos


(16) DATA:*23/05/2023 21:27:33*- TIPO:*ERROR*- MÉTODO:*GET*


      ID DO CARRINHO:9104
      <https://www.criadouropassaredo.com.br/loja/administra/index.php?controller=AdminCarts&token=633fe6f940a34230d22c363aeb11c421&id_cart=9104&viewcart>


      URL CHAMADA

https://api.pagseguro.com/charges/fees/calculate?value=500&max_installments=12&max_installments_no_interest=2&credit_card_bin=53


      DADOS ENVIADOS

null



      RESPOSTA DA API

{
     "error_messages": [
         {
             "error": "user_not_found",
             "description": "User not found, contact your account manager.",
             "parameter_name": "Authorization"
         }
     ]
}

Em 23/05/2023 18:10, PrestaBR escreveu:

**Comment by kkadm** [comment]
enviei ao ***@***.*** o acesso ao ADM da loja

Em 23/05/2023 18:10, PrestaBR escreveu:
