### ISSUE TITLE
CPF/CNPJ não preenche automático (dúvida/comentário)

### ISSUE THREAD

**Issue by glaucomodera** [pagseguro/pagseguro-modulo-prestashop#140]
### O que aconteceu?

Olá pessoal. 
Obrigado por desenvolver esse novo módulo com o PIX. 
Acontece que o campo CPF/CNPJ está sempre vazio e o cliente não consegue digitar o referido documento. Não habilita para digitar números - Tanto no Computador como no Mobile. O módulo só permite digitar o documento na opção de pagamento por cartão de crédito. Já no Boleto ou PIX não habilita e aparece o erro dizendo que esse campo é obrigatório. 

Outro detalhe é que eu acredito que as facilidades que foram implementadas no módulo pagseguro não foram inseridas no módulo pagbank. Exemplo: o módulo pagbank não reconhece o CPF do cliente cadastrado no site. Já o módulo pagseguro preenche automaticamente esse dado na hora de pagar. Inclusive eu solicitei essa facilidade nas atualizações do antigo pagseguro. 

Por favor, me ajude, pois eu estava há muito tempo aguardando o pagamento via PIX. 
Aproveito para renovar meus votos de estima e consideração. 
Abraços. 

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.2

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos

**Comment by prestabr** [comment]
Boa Tarde glaucomodera,

Esses campos não são nativos da PrestaShop e exigem o uso de módulo e ou customização direta no Core da Plataforma. Como existem inúmeros padrões de implementação dos campos e não é algo obrigatório optamos por remover a funcionalidade de preenchimento automático do CPF/CNPJ. Dessa forma, no ato do pagamento, o cliente digita e confere o CPF/CNPJ minimizando também problemas com o anti-fraude.

Essa dificuldade com o preenchimento dos campos pode estar relacionado com o seguinte:

- Verifica se o antigo módulo (PagSeguroPro) ainda está ativo, é preciso desativá-lo!;
- Verifica se existe algum conflito de JavaScript na tela de checkout, isso vai impedir o módulo de funcionar;
- Limpa o cache da loja em "Parâmetros Avançados > Desempenho";

Se você precisar, podemos disponibilizar um acesso ao nosso ambiente de testes para você conferir o funcionamento o módulo.

Atenciosamente,
Equipe PrestaBR

**Comment by glaucomodera** [comment]
Olá, obrigado pelo retorno. Eu questionei essa funcionalidade porque 90% dos meus clientes tentam finalizar o pedido com o cadastro incompleto. E meu site os obrigam a formalizar o cadastro antes do pagamento (justamente para cumprir as obrigações com a receita federal). Então o que está acontecendo na prática? O cliente clica para finalizar o pedido e recebe um aviso via modal concluir o cadastro. Ele digita o CPF (para concluir o cadastro) e é direcionado para pagamento. Em menos de 10 segundos o módulo pagbank o obriga a digitar o CPF novamente. Acredito que o cliente terá uma experiência de compra ruim se contiunar assim. 

Agora referente ao problema de preenchimento: 
Verifica se o antigo módulo (PagSeguroPro) ainda está ativo, é preciso desativá-lo!
R: Eu desativei durante os testes e depois voltei para o pagseguropro.

Verifica se existe algum conflito de JavaScript na tela de checkout, isso vai impedir o módulo de funcionar;
R: Vou verificar.

Limpa o cache da loja em "Parâmetros Avançados > Desempenho";
R: depois de verificar problemas de conflito de Java eu vou limpar cache e navegar em tela anônima para ter certeza que vai estar zerado.

**Comment by prestabr** [comment]
Boa Tarde glaucomodera,

Verificar e digitar os campos obrigatórios na tela de pagamento é algo fundamental para o fluxo do checkout, de forma alguma isso prejudica ou torna a experiência de compra ruim, também minimiza problemas com o anti-fraude caso o cartão não seja do titular do cadastro na loja.

Ok sobre os conflitos de JS e limpeza de cache. Se houver qualquer dificuldade, por favor, fique à vontade para entrar em contato novamente.

Desejamos Boas Vendas!

Atenciosamente,
Equipe PrestaBR
