### ISSUE TITLE
Dúvida, cadastro/adesão app.

### ISSUE THREAD

**Issue by cunha-fabricio** [pagseguro/pagseguro-modulo-prestashop#141]
### O que aconteceu?

estamos migrando do modulo antigo e nao foi possível informar o tipo de credencial, a combobox aparece apenas com uma opção chamada 'cadastre-se em algum dos apps.
<img width="1205" alt="Captura de Tela 2023-06-18 às 13 10 21" src="https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/58490559/b1b8b9c5-7974-4c81-a6dc-e5b2f35c02d3">

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.3

### Qual é a gravidade do problema?

Não consegui configurar o modulo

**Comment by prestabr** [comment]
Boa Tarde cunha-fabricio,

Antes de selecionar o App é preciso se cadastrar nele, você conseguiu seguir o fluxo de Cadastro/Adesão no App?
https://github.com/pagseguro/pagseguro-modulo-prestashop#1---cadastroades%C3%A3o-app

Escolhendo o App, clicando em "Cadastrar", irá abrir outra janela solicitando o login em sua conta no PagSeguro. Após o login, será exibida uma tela com as informações do App e o botão "Autorizar". Após autorizar, você será redirecionado novamente para a tela de configuração do módulo e a opção de selecionar o App estará disponível.

Atenciosamente,
Equipe PrestaBR
