### ISSUE TITLE
Loja & Hospedagem (Problema de permissão nos arquivos e diretórios na hospedagem / Config de grupo de clientes)

### ISSUE THREAD

**Issue by palexandrel** [pagseguro/pagseguro-modulo-prestashop#142]
### O que aconteceu?

Foi instalado o Modulo pagbank, no Prestashop, versão 8, mas toda vez que tento emitir uma venda, gera um erro, mesmo com todas aconfigurações feitas e em estado de "Produção", gera o erro: PagBank: Módulo não disponível. Por favor, verifique se o mesmo está ativo e cheque as Configurações do App. 

### Versão da PrestaShop?

PS 8.0

### Versão do PHP?

PHP 7.4

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos

**Comment by prestabr** [comment]
Boa Tarde palexandrel,

Essa mensagem é exibida na tela de checkout e indica que está pendente a selecionar o "Tipo de App" que deseja utilizar para processar os pagamentos.

Antes de selecionar o App é preciso se cadastrar nele, você conseguiu seguir o fluxo de Cadastro/Adesão no App?

1 - Cadastro/Adesão App
https://github.com/pagseguro/pagseguro-modulo-prestashop#1---cadastroades%C3%A3o-app

2 - Configurações do App (Para selecionar o Tipo de App)
https://github.com/pagseguro/pagseguro-modulo-prestashop#2---configura%C3%A7%C3%B5es-do-app

Atenciosamente,
Equipe PrestaBR

**Comment by palexandrel** [comment]
Bom dia, tudo bem com vocês?

As configurações, estão desta forma no link da imagem, mas mesmo assim ainda mostra o erro no momento de finalizar a compra, como mostra no link abaixo, com as configurações:

https://kidsvip.com.br/img-erro.jpg

**Comment by prestabr** [comment]
Bom Dia palexandrel,

Tudo bem!

Obrigado pelas informações no print. Você já conferiu se as permissões dos arquivos e diretórios estão configurados corretamente em sua hospedagem? O ideal é 644 para arquivos e 755 para diretórios.

Fizemos um cadastro em sua loja, mas não conseguimos seguir, se puder verificar:

![Screenshot at 2023-07-19 11-42-33](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/fe18adc3-d4b0-497c-880c-c7f8f5f3d810)

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde palexandrel,

As permissões nos arquivos e diretórios são premissas básicas de configuração da Plataforma PrestaShop, se não estiver configurado corretamente na hospedagem pode surgir alguns erros estranhos em sua loja. Essas permissões devem ser aplicadas de forma recursiva, pra tudo que estiver em sua /public_html/.

No print anterior, o erro era o 403:

![Screenshot at 2023-07-19 13-42-58](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/6b00fdc3-adc0-433a-8172-f308c31a294e)

Sobre o 403:

![Screenshot at 2023-07-19 13-43-23](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/db081935-e391-446e-b240-d8ed3b2a4c76)

Atenciosamente,
Equipe PrestaBR

**Comment by palexandrel** [comment]
Sim, estive pesquisando o erro na e acabei encontrando isso que, parece ser o erro que está causando:

Notice: SessionHandler::gc(): ps_files_cleanup_dir: opendir(/var/cpanel/php/sessions/ea-php74) failed: Permission denied (13)

Já estou em contato com a hospedagem para resolvermos isso. Desde já agradeço sua atenção e retorno nesta conversa.

**Comment by kkadm** [comment]
A 5 meses tentando fazer isso funcionar para o amigao diser que EU ESTOU FORÇANDO A BARRA, porque enviei uma UNICA print mostrando que o dados da estapa estavam CORRETOS!

REALMENTE 5 meses sem vender 1 centavo no pagseguro!

DESINSTALANDO E AGORA INSTALANDO **MERCADO PAGO** que funciona lindamente!

BOA SORTE! 

E SINCERAMENTE ESPERO QUE COLOQUEM PESSOAS COMPETENTES PARA ATENDER CLIENTES!

**Comment by prestabr** [comment]
Boa Tarde palexandrel,

Tudo bem?

Conseguiu ajustar as permissões em sua hospedagem?

Sabe se as configurações dos grupos de clientes e categorias estão corretas em sua loja? (nosso usuário logado não consegue acessar os produtos)

Qualquer dúvida ou problema, fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR

**Comment by palexandrel** [comment]
Olá! Tudo bem? Desculpe a demora em responder, estava realizando atualizações. Infelizmente, não foi possível atualizar e nem realizar as devidas correções. Tivemos que mudar as formas de pagamento. Mas desde já agradeço sua atenção e retorno nesta conversa.

**Comment by prestabr** [comment]
Bom Dia palexandrel,

Tudo bem!

Essas configurações básicas exigidas pela plataforma são bastante simples de corrigir, geralmente uma hospedagem do tipo VPS com cPanel ou DirectAdmin são o suficiente e elas já carregam as configurações por padrão.

Nesta tela, fizemos o cadastro na loja e clicamos em um produto e deu erro 403. Se não for problema de permissões na hospedagem é possívelmente um problema de configurações de grupo de usuários/categoria na loja. Isso impede compras, causa problemas de navegação, etc, independete do meio de pagamento.

![254644551-6b00fdc3-adc0-433a-8172-f308c31a294e](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/9f076515-47d2-45d7-a9b4-8554142ac670)

Se você quiser conhecer o módulo PagBank em nosso ambiente de testes ou precisar de auxílio com recomendação de hospedagem, por favor, fique à vontade para perguntar escrevendo para: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR
