### ISSUE TITLE
Boleto não são atualizado com status de pagamento (antigo módulo descontinuado pagseguropro)

### ISSUE THREAD

**Issue by rafaelsilvabra** [pagseguro/pagseguro-modulo-prestashop#143]
### O que aconteceu?

Boa tarde amigos,

Estou usando a versão anterior a essa nova que lançaram.
É obrigatório a migração?

Temos diversos boletos pagos no pagseguro, mostra que está confirmado quando abro o pedido do cliente, porém do lado de fora informa que não foi pago.
![3333](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/31866021/102e09fb-9b5b-4f2d-9c64-703e350e0c88)
![23332](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/31866021/1d28f37d-84dc-4ab9-998a-1f762c797733)

Podem dar uma luz do problema?
Obrigado

### Versão da PrestaShop?

PS 1.6

### Versão do PHP?

PHP 7.1

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Boa Tarde rafaelsilvabra,

> Estou usando a versão anterior a essa nova que lançaram. É obrigatório a migração?

O antigo módulo pagseguropro trabalha com Api v3, que tem planos de ser descontinuada em 31/12/23. O novo módulo pangbank já trabalha com a nova Api v4, que é mais moderna, rápida e segura.

O ideal é já migrar para o novo módulo, o processo é simples, basta instalar o novo e desativar o antigo. Na sequência segue o passo-a-passo:

1 - Cadastro/Adesão App
https://github.com/pagseguro/pagseguro-modulo-prestashop#1---cadastroades%C3%A3o-app

2 - Configurações do App
https://github.com/pagseguro/pagseguro-modulo-prestashop#2---configura%C3%A7%C3%B5es-do-app

Importante:

Sempre que você instalar ou atualizar o módulo, acesse a tab "Parâmetros Avançados > Desempenho" e clique em "Limpar Cache". Isso irá garantir que todos os arquivos sejam atualizados no cache da PrestaShop.

> Temos diversos boletos pagos no pagseguro, mostra que está confirmado quando abro o pedido do cliente, porém do lado de fora informa que não foi pago. ![3333](https://user-images.githubusercontent.com/31866021/260523115-102e09fb-9b5b-4f2d-9c64-703e350e0c88.png)

Esse print, ao acessar o pedido, apresenta uma consulta em tempo real na Api (no caso a v3) buscando todos os detalhes do pedido, incluindo o atual status.

>![23332](https://user-images.githubusercontent.com/31866021/260523152-1d28f37d-84dc-4ab9-998a-1f762c797733.png)

Esse print indica o atual status do pedido na sua loja.
Essa divergência deve ser por alguma dificuldade na hora de receber o callback da Api para atualizar o status do pedido na loja.
É possível verificar esses detalhes técnicos analisando os Logs e as informações sobre notificações dentro do pedido no PagSeguro.

A causa pode ser algum problema na loja/hospedagem ou versão desatualizada do antigo módulo pagseguropro.

A sugestão é fazer a migração, nessa nova versão também tem Pix...

> 
> Podem dar uma luz do problema? Obrigado
> 
> ### Versão da PrestaShop?
> PS 1.6
> 
> ### Versão do PHP?
> PHP 7.1
> 
> ### Qual é a gravidade do problema?
> Um dos métodos de pagamento não está funcionando

Atenciosamente,
Equipe PrestaBR
