### ISSUE TITLE
eu estou com um problema no chekaut do pague seguro [Question]: 

### ISSUE THREAD

**Issue by erirtyrty** [pagseguro/pagseguro-modulo-prestashop#144]
### Qual é a sua dúvida, como podemos ajudar?

gente o cara mandou uma mensagem pra min so que eu nao sei fazer O arquivo que te passei é para ser usado com o postman para que você desenvolva as chamadas junto a sua aplicação/site, não é um PDF e sim linhas de comando (codigo em json). 

 

### Versão da PrestaShop

PS 1.6

**Comment by prestabr** [comment]
Boa Tarde erirtyrty,

Tudo bem?

Não entendemos a sua dúvida/pergunta, se puder reformular...

Mas se você decidir usar o módulo de integração PagBank em sua loja PrestaShop basta fazer o download e seguir o passo-a-passo de instalação e configuração. Não é necessário conhecimento técnico, linha de comando e/ou manipulação de código/json.

Instalação
https://github.com/pagseguro/pagseguro-modulo-prestashop#instala%C3%A7%C3%A3o-ou-atualiza%C3%A7%C3%A3o

Configuração
1 - Cadastro/Adesão App
https://github.com/pagseguro/pagseguro-modulo-prestashop#1---cadastroades%C3%A3o-app

2 - Configurações do App
https://github.com/pagseguro/pagseguro-modulo-prestashop#2---configura%C3%A7%C3%B5es-do-app

Doc Completa e Download do módulo: https://github.com/pagseguro/pagseguro-modulo-prestashop

Qualquer dúvida, fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR
