### ISSUE TITLE
[Bug]: Get Sucess dados enviados null

### ISSUE THREAD

**Issue by WebGF** [pagseguro/pagseguro-modulo-prestashop#145]
### O que aconteceu?

Alguns clientes não estão conseguindo concluir compra com cartão de credito.
O primeiro log do carrinho da GET SUcess, mas dados enviados marca null. Todos os logs consequentes da Error, dados enviados null, resposta da api null.
![logsError](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/56832697/6e711210-4f6b-4ef3-85db-0572af3fb929)
![Imagem do WhatsApp de 2023-08-29 à(s) 12 30 19](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/56832697/ea81f614-ff69-43fe-b915-7271739d6abc)
![Imagem do WhatsApp de 2023-08-29 à(s) 12 30 28](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/56832697/89a6731f-afa9-4386-b76b-605a2cc3c86c)
![logGet](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/56832697/f9bfaa0a-6c2a-4302-9cbb-d6818b518bbb)
![logs](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/56832697/27a057ea-d620-4376-9bb2-a069fac857fb)

### Versão da PrestaShop?

PS 1.6

### Versão do PHP?

PHP 5.6

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Tudo bem?

Para organizar e simplificar o entendimento segue comentários abaixo de cada print.

> ### O que aconteceu?
> Alguns clientes não estão conseguindo concluir compra com cartão de credito. O primeiro log do carrinho da GET SUcess, mas dados enviados marca null. Todos os logs consequentes da Error, dados enviados null, resposta da api null. ![logsError](https://user-images.githubusercontent.com/56832697/264139602-6e711210-4f6b-4ef3-85db-0572af3fb929.JPG)

Com Log em branco, sem um contexto definido não há como saber o que houve. Vamos descartar esse print e seguir para o próximo...

![Imagem do WhatsApp de 2023-08-29 à(s) 12 30 19](https://user-images.githubusercontent.com/56832697/264139609-ea81f614-ff69-43fe-b915-7271739d6abc.jpg)

Indica que o cliente preencheu os campos e clicou em pagar, o pagamento está sendo processado.

![Imagem do WhatsApp de 2023-08-29 à(s) 12 30 28](https://user-images.githubusercontent.com/56832697/264139613-89a6731f-afa9-4386-b76b-605a2cc3c86c.jpg) 
 
A mensagem sinaliza que houve algum erro ao processar o pagamento. 
Acessando a área de Logs do módulo pesquisa pelo ID do Carrinho ou por Type = error e Method = post. 

![logGet](https://user-images.githubusercontent.com/56832697/264139619-f9bfaa0a-6c2a-4302-9cbb-d6818b518bbb.JPG)

Este log/print indica que o cliente, na tela de checkout, informou o número do cartão e obteve as opções de parcelamento para seguir com o pagamento. No print abaixo é o log ID 87.

![logs](https://user-images.githubusercontent.com/56832697/264139622-27a057ea-d620-4376-9bb2-a069fac857fb.JPG)

Confere que existem 4 tentativas de pagamento indicando erro para o carrinho 16808.
Acessa algum desses 4 logs e localiza a área "RESPOSTA DA API". Nesta área vai existir o motivo do erro, indicado pela API. Tira um print e posta aqui pra gente analisar por favor.

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
Bom dia, obrigado pelo retorno.
As quatro tentativas do carrinho 16808 retornaram a mesma mensagem:
![error](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/56832697/4a79ab4a-173c-4f27-9ff2-32748f20ed59)

**Comment by prestabr** [comment]
Bom Dia WebGF,

Obrigado pelas informações.

Esse não é comportamento padrão do módulo, quando a opção "Gerar LOGs completos" está ativa tudo o que é enviado e recebido fica registrado. Com o Log em branco, parece que o módulo não chega a tentar processar o pagamento.

Em nosso ambiente de testes e homologações não conseguimos reproduzir este problema, por conta disso sugerimos que você faça algumas verificações em sua loja/hospedagem:

1) Confere se as permissões dos arquivos e diretórios estão configuradas corretamente em sua hospedagem. O ideal é 644 para arquivos e 755 para diretórios. Essas permissões devem ser aplicadas de forma recursiva, pra tudo que estiver em sua /public_html/.

2) Se você substituiu o antigo módulo pagseguropro pelo pagbank, certifique-se que o pagseguropro esteja desativado e que o cache da prestashop esteja limpo. Para que seja carregado somente os arquivos do módulo pagbank na tela de checkout. Se for só você que está testando e com muita frequência, pode ser uma boa limpar o cache do seu navegador também.

3) Desativa o debug da PrestaShop, na 1.6 fica na /public_html/config/defines.inc.php, na linha define('_PS_MODE_DEV_', false).

4) Em sua tela de checkout, abre o inspetor de elementos do navegador e clica na tab console. Verifica se existe algum erro de JavaScript.

Aguardamos seu retorno.

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
1 - ainda vou executar.
2 - sim estou atualizando do modulo antigo do pagSeguroPro para o PagBank. Alias uma das instruções para mim não esta muito clara. Eu desinstalo o modulo antigo(PagSeguroPro) ou só desabilito?
3 - ja esta false.
4 - nenhum alerta de erro de javascript

**Comment by prestabr** [comment]
Olá WebGF,

1. Ok, essa config é importante porque é requisito básico da plataforma PrestaShop, quando não configurado pode surgir alguns problemas de funcionamento na loja ou módulos.
2. A gente sugere só desabilitar o pagseguropro pra não perder os dados de configuração do módulo. Assim você pode instalar e testar o pagbank e caso algo dê errado você pode reativar o módulo antigo até resolver os problemas com o novo. 
3. Ok.
4. Ótimo.

Quando você conseguir fazer os ajustes das permissões é só limpar o cache da PS e testar o módulo na tela de checkout.

Aguardamos seu retorno!

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
1- conclui essa etapa parece que resolveu

**Comment by prestabr** [comment]
Boa Tarde WebGF,

Agradecemos o seu feedback e desejamos Boas Vendas! :)

Qualquer dúvida ou problema, por favor, fique à vontade para retornar o contato.

Atenciosamente,
Equipe PrestaBR
