### ISSUE TITLE
Config loja & hospedagem

### ISSUE THREAD

**Issue by jagunsow** [pagseguro/pagseguro-modulo-prestashop#146]
### O que aconteceu?

estou tendo o seguinte erro com esse módulo:
Detalhes da transação
PagBank: Módulo não disponível. Por favor, verifique se o mesmo está ativo e cheque as Configurações do App.

para investigar subistitui a linha dessa mensagem de erro por uma de detalhes:

$pagbank_msg = $this->l('PagBank: Módulo não disponível. Por favor, verifique se o mesmo está ativo e cheque as Configurações do App.') . 
" (Active: " . var_export($this->active, true) . 
", Check Currency: " . var_export($this->checkCurrency($params['cart']), true) . 
", Ready: " . var_export($this->ready, true) . 
", Token: " . var_export($this->token, true) . 
", Public Key: " . var_export($this->public_key, true) . 
", Public Key from Configuration: " . var_export(Configuration::get('PAGBANK_PUBLIC_KEY'), true) . 
", Public Key Sandbox from Configuration: " . var_export(Configuration::get('PAGBANK_PUBLIC_KEY_SANDBOX'), true) . ")";

e o resultado é 
(Active: 1, Check Currency: true, Ready: false, Token: false, Public Key: false, Public Key from Configuration: false, Public Key Sandbox from Configuration: false)

olhando na tabela 'ps_configuration' não existe mesmo a linha PAGBANK_PUBLIC_KEY_SANDBOX e nem a PAGBANK_PUBLIC_KEY
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/4911197/7cce7be0-f349-495b-b142-ed9acf16e4ef)

![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/4911197/ae287933-cb35-45d3-aa73-a06b61fdd7da)

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.2

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos

**Comment by jagunsow** [comment]
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/4911197/4790c5a8-3e1f-40b0-a111-1833ca2e875a)

**Comment by prestabr** [comment]
Boa Noite jagunsow,

Obrigado pelas informações.

Esse não é comportamento padrão do módulo, em nosso ambiente de testes e homologações não conseguimos reproduzir este problema.

Após seguir o fluxo de Cadastro/Adesão no App é importante selecionar o Tipo de Credencial que irá processar os Pagamentos na sessão Configurações do App.

1 - Cadastro/Adesão App
https://github.com/pagseguro/pagseguro-modulo-prestashop#1---cadastroades%C3%A3o-app

2 - Configurações do App
https://github.com/pagseguro/pagseguro-modulo-prestashop#2---configura%C3%A7%C3%B5es-do-app

> ![image](https://user-images.githubusercontent.com/4911197/269403758-4790c5a8-3e1f-40b0-a111-1833ca2e875a.png)

Depois que você seguiu o fluxo de Cadastro/Adesão e os Logs ID 1, 2 e 3 (print acima) foram registrados, além de não salvar no banco de dados, você já conferiu se esses Logs estão em branco (clica neles)?

Esse comportamento caracteriza problemas de permissões nos arquivos e diretórios na hospedagem. O ideal é 644 para arquivos e 755 para diretórios. Essas permissões devem ser aplicadas de forma recursiva, pra tudo que estiver em sua /public_html/.

Aguardamos seu retorno.

Atenciosamente,
Equipe PrestaBR

**Comment by jagunsow** [comment]
Obrigado pela resposta vo tentarei novamente mais tarde, 
estou tendo outro erro agora pode ser que seja intermitente>
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/4911197/2b1d36f6-6b1e-4a2f-9b6f-37fe44d08248)

**Comment by prestabr** [comment]
Olá jagunsow,

> Obrigado pela resposta tentarei novamente mais tarde, estou tendo outro erro agora pode ser que seja intermitente> ![image](https://user-images.githubusercontent.com/4911197/269646024-2b1d36f6-6b1e-4a2f-9b6f-37fe44d08248.png)

Essa tela é o debug da loja ligado indicando que não foi possível executar, conectar e ou ler alguma info do banco. Não é erro de programação e/ou bug do módulo. Confere as configs da sua hospedagem... 

> ![image](https://user-images.githubusercontent.com/4911197/269646533-9a8c21a8-ea8f-4ff4-9787-56d652f044aa.png)

Essas permissões devem ser aplicadas de forma recursiva, pra tudo que estiver em sua /public_html/. Essa config é importante porque é requisito básico da plataforma PrestaShop, quando não configurado pode surgir alguns problemas de funcionamento na loja ou módulos.

Depois de revisar essas configs de hospedagem, tenta desinstalar e reinstalar o módulo, limpa o cache da PS e faz novamente o fluxo de Adesão que deve funcionar corretamente.

Atenciosamente,
Equipe PrestaBR
