### ISSUE TITLE
Não consigo cadastrar o módulo em nenhuma modalidade de taxa App D30.... (SANDBOX)

### ISSUE THREAD

**Issue by codeLearnerrr** [pagseguro/pagseguro-modulo-prestashop#148]
### O que aconteceu?

Instalei o módulo e na etapa de cadastrar a modalidade de taxa recebo o erro abaixo da Pagbank
![pagbank-error](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/44307139/8f309186-65b6-42f6-b881-e5700588a371)

Simplesmente segui o manual e não funcionou. 

### Versão da PrestaShop?

PS 8.0

### Versão do PHP?

PHP 7.2

### Qual é a gravidade do problema?

Não consegui configurar o modulo

**Comment by prestabr** [comment]
Boa Noite codeLearnerrr,

Por enquanto estamos com a opção do SandBox em desuso devido à algumas updates do módulo e API. Tenta fazer o cadastro no Modo Produção que irá funcionar normalmente.

P/ a próxima update do módulo, em +- 30 dias, temos em nosso backlog algumas updates p/ melhorias e correções que também irão abranger o SandBox.

Atenciosamente,
Equipe PrestaBR

**Comment by codeLearnerrr** [comment]
Olá. Tentei o cadastro no modo de produção e também não funcionou. 
![pagbank-error-production](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/44307139/7f25e112-ded9-4c9b-b743-3b40e73ee820)

Preciso do plugin funcionando.

**Comment by prestabr** [comment]
Bom Dia codeLearnerrr

Em nosso ambiente de testes e homologações não conseguimos reproduzir este problema com o ambiente de produção.
Esse comportamento caracteriza problemas de permissões nos arquivos e diretórios na sua hospedagem. 
O ideal é 644 para arquivos e 755 para diretórios. 
Essas permissões devem ser aplicadas de forma recursiva, pra tudo que estiver em sua /public_html/. 
Essa config é importante porque é requisito básico da plataforma PrestaShop, quando não configurado podem surgir alguns problemas de funcionamento na loja ou módulos.

Atenciosamente,
PrestaBR
