### ISSUE TITLE
Erro de JS na validação de Cartão (config de permissões na hospedagem ou cartão de teste)

### ISSUE THREAD

**Issue by douglascarlini** [pagseguro/pagseguro-modulo-prestashop#149]
### O que aconteceu?

Ao preencher o número do cartão na tela de checkout, surge este erro:

<img width="920" alt="image" src="https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/22769198/95665e33-f2cc-4893-b651-d87961450d8e">

PrestaShop: 8.1.2 e 8.0.5
PHP: 8.1.26

### Versão da PrestaShop?

PS 8.0

### Versão do PHP?

PHP 8.1

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos, Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Bom Dia douglascarlini,

Em nosso ambiente de testes e homologações não conseguimos reproduzir este problema na validação do cartão.
O comportamento fora do esperado está comumente relacionado à problemas de permissões nos arquivos e diretórios na hospedagem. O ideal é 644 para arquivos e 755 para diretórios.

Essas permissões devem ser aplicadas de forma recursiva, pra tudo que estiver em sua /public_html/. Essa config é importante porque é requisito básico da plataforma PrestaShop, quando não configurado podem surgir alguns problemas de funcionamento na loja ou módulos. https://docs.prestashop-project.org/v.8-documentation/getting-started/installing-prestashop#updating-chmod

Após conferir as permissões acessa a tab de Logs do módulo para conferir a comunicação com a API. https://github.com/pagseguro/pagseguro-modulo-prestashop#5---debug--logs

Exemplo em funcionamento:

https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/8726305a-5ba7-4050-ad1b-aae1db07d27f



Atenciosamente,
Equipe PrestaBR

**Comment by douglascarlini** [comment]
Bom dia @prestabr,

Como pode ver, todos os arquivos e diretórios estão em modo 777, logo, não deveria haver problemas de permissão.

<img width="875" alt="image" src="https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/22769198/66e43e6e-3eff-4f71-999e-beaa24df0a48">

<img width="1198" alt="image" src="https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/22769198/64a85ffb-2797-433f-bd23-ed2781cac629">

<img width="532" alt="image" src="https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/22769198/5e664603-77ca-4cf7-a36d-ac1b59c16173">
