### ISSUE TITLE
QRCode gerado não é reconhecido pelo App do Banco

### ISSUE THREAD

**Issue by kidultttttt** [pagseguro/pagseguro-modulo-prestashop#150]
### O que aconteceu?

Olá! Está tudo OK com nossa conta do PagBank, existe uma chave PIX cadastrada lá, no eCommerce a compra é finalizada e o QRCode é gerado. Ao ler no aplicativo do banco para pagamento, diz que o QRCode está inválido. Existe alguma configuração que está faltando?

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.3

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Boa Tarde kidultttttt,

Verifica se o prazo para o pagamento do Pix já exipirou, o prazo padrão do Pix é 30 minutos. Mais infos: https://github.com/pagseguro/pagseguro-modulo-prestashop?tab=readme-ov-file#3---configura%C3%A7%C3%B5es-de-pagamento

Caso não tenha expirado, tente fazer o pagamento via outro banco/app. Pode ser que o serviço do banco pagador esteja com alguma indisponibilidade pontual/temporária.

Atenciosamente,
Equipe PrestaBR

**Comment by kidultttttt** [comment]
> Boa Tarde kidultttttt,
> 
> Verifica se o prazo para o pagamento do Pix já expirou, o prazo padrão do Pix é 30 minutos. Mais infos: https://github.com/pagseguro/pagseguro-modulo-prestashop?tab=readme-ov-file#3---configura%C3%A7%C3%B5es-de-pagamento
> 
> Caso não tenha expirado, tente fazer o pagamento via outro banco/app. Pode ser que o serviço do banco pagador esteja com alguma indisponibilidade pontual/temporária.
> 
> Atenciosamente, Equipe PrestaBR

Olá. O prazo para expiração está configurado para 30 minutos, a tentativa de pagamento foi realizada antes da expiração, em mais de um banco, sem sucesso.

**Comment by prestabr** [comment]
Bom Dia kidultttttt,

Em nosso ambiente de testes e homologações não conseguimos reproduzir este problema. Também verificamos em algumas lojas e tudo está funcionando normalmente, incluindo os serviços do PagBank.

> Olá. O prazo para expiração está configurado para 30 minutos, a tentativa de pagamento foi realizada antes da expiração, em mais de um banco, sem sucesso.

1. Essa informação é baseada em algum pedido específico e no que o cliente te falou? Se sim, é difícil ter certeza sobre o prazo e as tentativas de pagamentos.
2. Você tentou criar um pedido pra testar a tentou fazer o pagamento pra conferir? Se sim, confere também no App do PagBank, na mesma conta onde foi feita a adesão do módulo, se realmente só existe uma chave pro Pix.

Atenciosamente,
Equipe PrestaBR

**Comment by kidultttttt** [comment]
Olá!

Não é nenhuma transação de cliente. Foi uma venda realizada como teste por nós mesmo. Aumentamos a expiração agora pra 48 horas, tentamos realizar o pagamento, mas não funcionou.

Existe apenas uma chave PIX cadastrada no painel do PagBank, somente uma.

Em contato com o Suporte do PagBank eles disseram que tínhamos que gerar um Token pelo painel deles, para que esse Token fosse usado. Verificando a documentação e o painel de configuração do Módulo não constatei nenhum local onde pudéssemos informar tal Token. Poderia me instruir?

**Comment by prestabr** [comment]
Olá kidultttttt,

> Olá!
> 
> Não é nenhuma transação de cliente. Foi uma venda realizada como teste por nós mesmo. Aumentamos a expiração agora pra 48 horas, tentamos realizar o pagamento, mas não funcionou.

Não precisa aumentar o prazo de vencimento, a única utilidade é fazer o QRCode expirar.

> Existe apenas uma chave PIX cadastrada no painel do PagBank, somente uma.

Ok.

> Em contato com o Suporte do PagBank eles disseram que tínhamos que gerar um Token pelo painel deles, para que esse Token fosse usado. Verificando a documentação e o painel de configuração do Módulo não constatei nenhum local onde pudéssemos informar tal Token. Poderia me instruir?

Desconsidera, essa informação sobre o Token não faz sentido para a integração com este módulo.

Consegue liberar o ambiente de testes pra gente acessar e conferir todos os detalhes? Se sim, por favor envia os acessos pra: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR

**Comment by kidultttttt** [comment]
Eu fiz um novo teste a menos de 20 minutos, após gerar o Token que o pessoal pediu, por algum motivo, agora está funcionando.

**Comment by prestabr** [comment]
Olá kidultttttt,

Talvez fosse alguma questão interna/pontual em sua conta lá no PagBank e o atendente lançou os ajustes.

Obrigado pelo feedback, desejamos boas-vendas! Marca a opção para receber notificações sobre o repositório, mês que vem estaremos lançando nova update com melhorias e correções.

Atenciosamente,
Equipe PrestaBR
