### ISSUE TITLE
Segunda via do boleto pelo site prestashop?

### ISSUE THREAD

**Issue by WebGF** [pagseguro/pagseguro-modulo-prestashop#151]
### Qual é a sua dúvida, como podemos ajudar?

Boa tarde, tenho um instalação em prestashop 1.6 com o novo modulo do pagbank. Um cliente finalizou a compra via boleto mas ocorreu algum erro no navegador e a pagina com o botão para baixar o boleto não carregou. 
Dentro do proprio site é possivel reenviar o boleto para o cliente?
Desde ja agradeça a atenção.
Att. Mauricio

### Versão da PrestaShop

PS 1.6

**Comment by prestabr** [comment]
Bom Dia Mauricio,

A loja não envia o link do boleto por email, também não tem opção de reenvio. Mas no histórico do pedido gerado, tem um bloco com todas as informações e o link do boleto em pdf, exemplo:

![Screenshot at 2024-01-15 10-01-23](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/0112f29d-0d37-4a1b-ac87-ab832778c005)

Vamos considerar essa opção de reenvio p/ as próximas updates.

Atenciosamente,
Equipe PrestaBR
