### ISSUE TITLE
Config de desconto & atualização do módulo v.1.3.0

### ISSUE THREAD

**Issue by kidultttttt** [pagseguro/pagseguro-modulo-prestashop#152]
### O que aconteceu?

Olá, estamos finalizando os testes em nosso site.

Fomos finalizar algumas vendas para ver se tudo corria bem, mas batemos de frente com um problema chato.

As vendas por PIX estão gerando QRCodes com valor de pagamento inferior ao valor real da compra.

Como podemos solucionar?

Obs1.: configurei agora o PIX para ser válido durante 72 horas, para ser possível realizar testes com mais eficácia.
Obs2.: URL do site: https://demaislindamulher.com.br/

Valores referentes a venda:
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/54eeaf15-b12a-4293-8f73-0ac8989fbc74)

QRCode PIX gerado:
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/147a8f7f-ee36-480b-bb0f-6d4e68e02bb0)

Copia e cola: 00020101021226830014br.gov.bcb.pix2561api.pagseguro.com/pix/v2/CCE9B7D6-FB43-47F5-8033-3ADBCEB70DE927600016BR.COM.PAGSEGURO0136CCE9B7D6-FB43-47F5-8033-3ADBCEB70DE95204566153039865406249.765802BR5922DEMAIS LINDA MULHER LT6007Goiania62070503***63042015

Outras informações:
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/f2d2eb01-9627-4ccb-a7fe-a906af2fb603)

Obrigado.

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.3

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Boa Noite kidultttttt,

Obrigado por utilizar o módulo oficial e entrar em contato conosco.

O link da loja está em manutenção, https://demaislindamulher.com.br/, não conseguimos acessar para testar.

Conferimos em nosso ambiente de testes e homologações e não conseguimos identificar essa divergência de centavos utilizando a opção de desconto no meio de pagamento, nas mesmas condições do exemplo do seu print.

Em seu teste você já estava utilizando a nova versão do módulo v.1.3.0?

Aproveitando, acabamos de lançar uma nova update, v.1.3.1 com novas correções e melhorias. Assim que você atualizar, por favor, volte aqui para nos contar sobre.

Atenciosamente,
Equipe PrestaBR

**Comment by kidultttttt** [comment]
Olá, a versão que estamos utilizando é a seguinte: PagBank - Checkout Transparente - v.1.2.0

Vou realizar a atualização do módulo e retorno com o feedback. Por favor, não fechar essa issue, se possível.

Por favor, poderia disponibilizar um IP para que eu possa adicionar a whitelist para conseguirem navegar no site, tendo em vista que ainda não podemos abrir ao público, pois já temos uma clientela que pode vir a comprar no site se retirarmos do modo de manutenção.

Obrigado.

**Comment by prestabr** [comment]
Oi kidultttttt,

Não vamos conseguir te passar o IP por aqui, mas pode atualizar o módulo em sua loja que vamos aguardar o seu feeback pra fechar a issue.

Depois que você atualizar, limpa o cache da PS e do seu navegador para realizar os testes.

Atenciosamente,
Equipe PrestaBR

**Comment by kidultttttt** [comment]
Obrigado, após atualizar o módulo para a versão v1.3.1 os QRCodes PIX agora estão sendo criados com os valores corretos.

Vou aproveitar e tirar outra dúvida neste mesmo tópico.

Realizamos uma compra e fizemos o pagamento via PIX, o valor já foi conferido na plataforma do PagBank e está disponível. O problema é que a situação do pedido no PrestaShop não foi atualizada, continua como PagBank - Aguardando Pagamento.

Realmente o PIX, quando pago, não atualiza o status do pedido no Painel do PrestaShop? Deve ser feito manualmente a confirmação do pagamento na plataforma do PagBank e depois atualizado no Painel?

Pedido com situação não atualizada:
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/17fa3321-b62e-4299-a607-475b03435809)

Dados do pedido:
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/4252272f-eba0-4594-895a-df2cc027a3a7)

Esse PIX do pedido foi pago com sucesso!

**Comment by kidultttttt** [comment]
Complementando sobre o pedido #8.

Nos logs do PagBank houve uma consulta que retornou o status de PAGO para esse pedido, mas mesmo assim o status do pedido não foi atualizado.

![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/bb0f7fdd-3341-4fdf-a958-77c49126576d)

ID 33 (criação da chave PIX para pagamento):

URL Chamada:
https://api.pagseguro.com/orders/ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71

Dados enviados:
null

Resposta da API:
{
    "id": "ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71",
    "reference_id": "19.D14.377990",
    "created_at": "2024-01-17T16:10:35.618-03:00",
    "customer": "##########",
    "items": [
        {
            "reference_id": "255",
            "name": "LOI1002.2 LIVIA CARAMELO ",
            "quantity": 1,
            "unit_amount": 23990
        }
    ],
    "shipping": "##########",
    "qr_codes": [
        {
            "id": "QRCO_5D5F85EE-6587-4E81-8B3C-2F801AF82F7B",
            "expiration_date": "2024-01-17T16:40:35.000-03:00",
            "amount": {
                "value": 23836
            },
            "text": "00020101021226830014br.gov.bcb.pix2561api.pagseguro.com/pix/v2/5D5F85EE-6587-4E81-8B3C-2F801AF82F7B27600016BR.COM.PAGSEGURO01365D5F85EE-6587-4E81-8B3C-2F801AF82F7B5204566153039865406238.365802BR5922DEMAIS LINDA MULHER LT6007Goiania62070503***63047DA8",
            "arrangements": [
                "PIX"
            ],
            "links": [
                {
                    "rel": "QRCODE.PNG",
                    "href": "https://api.pagseguro.com/qrcode/QRCO_5D5F85EE-6587-4E81-8B3C-2F801AF82F7B/png",
                    "media": "image/png",
                    "type": "GET"
                },
                {
                    "rel": "QRCODE.BASE64",
                    "href": "https://api.pagseguro.com/qrcode/QRCO_5D5F85EE-6587-4E81-8B3C-2F801AF82F7B/base64",
                    "media": "text/plain",
                    "type": "GET"
                }
            ]
        }
    ],
    "notification_urls": [
        "https://demaislindamulher.com.br/modules/pagbank/notify.php"
    ],
    "links": [
        {
            "rel": "SELF",
            "href": "https://api.pagseguro.com/orders/ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71",
            "media": "application/json",
            "type": "GET"
        },
        {
            "rel": "PAY",
            "href": "https://api.pagseguro.com/orders/ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71/pay",
            "media": "application/json",
            "type": "POST"
        }
    ]
}

ID 38 (confirmação do pagamento):

URL Chamada:
https://api.pagseguro.com/orders/ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71

Dados enviados:
null

Respota da API:
{
    "id": "ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71",
    "reference_id": "19.D14.377990",
    "created_at": "2024-01-17T16:10:35.618-03:00",
    "customer": "##########",
    "items": [
        {
            "reference_id": "255",
            "name": "LOI1002.2 LIVIA CARAMELO ",
            "quantity": 1,
            "unit_amount": 23990
        }
    ],
    "shipping": "##########",
    "qr_codes": [
        {
            "id": "QRCO_5D5F85EE-6587-4E81-8B3C-2F801AF82F7B",
            "expiration_date": "2024-01-17T16:40:35.000-03:00",
            "amount": {
                "value": 23836
            },
            "text": "00020101021226830014br.gov.bcb.pix2561api.pagseguro.com/pix/v2/5D5F85EE-6587-4E81-8B3C-2F801AF82F7B27600016BR.COM.PAGSEGURO01365D5F85EE-6587-4E81-8B3C-2F801AF82F7B5204566153039865406238.365802BR5922DEMAIS LINDA MULHER LT6007Goiania62070503***63047DA8",
            "arrangements": [
                "PIX"
            ],
            "links": [
                {
                    "rel": "QRCODE.PNG",
                    "href": "https://api.pagseguro.com/qrcode/QRCO_5D5F85EE-6587-4E81-8B3C-2F801AF82F7B/png",
                    "media": "image/png",
                    "type": "GET"
                },
                {
                    "rel": "QRCODE.BASE64",
                    "href": "https://api.pagseguro.com/qrcode/QRCO_5D5F85EE-6587-4E81-8B3C-2F801AF82F7B/base64",
                    "media": "text/plain",
                    "type": "GET"
                }
            ]
        }
    ],
    "charges": [
        {
            "id": "CHAR_5E1CDF33-77D4-485D-B5C3-A7C4F2714EEF",
            "reference_id": "19.D14.377990",
            **"status": "PAID"**,
            "created_at": "2024-01-17T16:18:28.621-03:00",
            **"paid_at": "2024-01-17T16:18:29.948-03:00"**,
            "amount": {
                "value": 23836,
                "currency": "BRL",
                "summary": {
                    "total": 23836,
                    "paid": 23836,
                    "refunded": 0
                }
            },
            "payment_response": {
                "code": "20000",
                "message": "SUCESSO"
            },
            "payment_method": {
                "type": "PIX",
                "pix": {
                    "notification_id": "NTF_A9293B99-F944-4323-80DD-29E7C00ABF3C",
                    "end_to_end_id": "E60701190202401171913DY55UIDO93K",
                    "holder": {
                        "name": "LUANA CARVALHO MENDES MACHADO",
                        "tax_id": "***508681**"
                    }
                }
            },
            "links": [
                {
                    "rel": "SELF",
                    "href": "https://api.pagseguro.com/charges/CHAR_5E1CDF33-77D4-485D-B5C3-A7C4F2714EEF",
                    "media": "application/json",
                    "type": "GET"
                },
                {
                    "rel": "CHARGE.CANCEL",
                    "href": "https://api.pagseguro.com/charges/CHAR_5E1CDF33-77D4-485D-B5C3-A7C4F2714EEF/cancel",
                    "media": "application/json",
                    "type": "POST"
                }
            ],
            "metadata": {}
        }
    ],
    "notification_urls": [
        "https://demaislindamulher.com.br/modules/pagbank/notify.php"
    ],
    "links": [
        {
            "rel": "SELF",
            "href": "https://api.pagseguro.com/orders/ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71",
            "media": "application/json",
            "type": "GET"
        },
        {
            "rel": "PAY",
            "href": "https://api.pagseguro.com/orders/ORDE_5C6D26DF-7EE2-4145-A90C-5E17FC331D71/pay",
            "media": "application/json",
            "type": "POST"
        }
    ]
}

**Comment by prestabr** [comment]
Olá kidultttttt,

Ótimo, obrigado pelo feedback. Desejamos Boas-Vendas! :)

A atualização de status é toda automatizada, p/ cartão/boleto/pix.

No caso do Pix, alguns segundos após a confirmação do pagamento, chega uma notificação de atualização de status.
Se você estiver na tela de confirmação do pedido você é redirecionado p/ o histórico já com status atualizado.
O redirecionamento só não irá ocorrer se houver algum erro de JavaScript em sua loja (confere no inspetor de elementos).
Se você estiver no histórico do pedido no backoffice, atualiza a página p/ ver a atualização do status recebida.

Você também pode conferir o recebimento das notificações p/ atualização de status na área de Logs: https://github.com/pagseguro/pagseguro-modulo-prestashop?tab=readme-ov-file#5---debug--logs

Exemplo de notificação recebida:
![Screenshot at 2024-01-18 01-08-30](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/0c99c9e4-98eb-468a-9ca4-f73a8c4a4d9e)

Se você não estiver recebendo nenhuma notificação talvez possa ser a loja em modo manutenção bloqueando o recebimento.

Atenciosamente,
Equipe PrestaBR

**Comment by kidultttttt** [comment]
Está tudo correto, o recebimento das notificações está ocorrendo normalmente.

O problema é que mesmo recebendo a notificação de pagamento efetuado, o Status do pedido não está sendo atualizado.

![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/c3c4f610-4a64-498c-918b-a42891067fac)

Estas são as notificações referentes ao pedido número 8, citado acima.

O ID 33 é a criação do QRCode PIX para pagamento.

O ID 38 é o retorno de que o pagamento foi realizado com sucesso.
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/155018380/33b82bd6-03d6-498c-9ce1-8bb0626540f1)

Mesmo com esse retorno de pagamento efetuado não houve atualização do Status do pedido.

**Comment by prestabr** [comment]
Olá kidultttttt,

> Está tudo correto, o recebimento das notificações está ocorrendo normalmente.
> 
> O problema é que mesmo recebendo a notificação de pagamento efetuado, o Status do pedido não está sendo atualizado.
> 
> ![image](https://private-user-images.githubusercontent.com/155018380/297613011-c3c4f610-4a64-498c-918b-a42891067fac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTIyNTAsIm5iZiI6MTcwNTU1MTk1MCwicGF0aCI6Ii8xNTUwMTgzODAvMjk3NjEzMDExLWMzYzRmNjEwLTRhNjQtNDk4Yy05MThiLWE0Mjg5MTA2N2ZhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwNDI1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzhkNTkyNzlmNGFjMjdkMWMyNTNlY2I2YmY5MWEyZTEyZjgwYTY0OGE0YTM5ODRmOWMzMjdlNzgzYzNlNDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rEXbVutzi-eZ4WUiqOaiuJT9ilcPC_DpejZ_MvpWFTc)

A notificação é method callback, não é method GET.
GET é consulta, não realiza troca de status.

> 
> Estas são as notificações referentes ao pedido número 8, citado acima.
> 
> O ID 33 é a criação do QRCode PIX para pagamento.
> 
> O ID 38 é o retorno de que o pagamento foi realizado com sucesso. ![image](https://private-user-images.githubusercontent.com/155018380/297613626-33b82bd6-03d6-498c-9ce1-8bb0626540f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTIyNTAsIm5iZiI6MTcwNTU1MTk1MCwicGF0aCI6Ii8xNTUwMTgzODAvMjk3NjEzNjI2LTMzYjgyYmQ2LTAzZDYtNDk4Yy05Y2UxLThiYjA2MjY1NDBmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQwNDI1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Zjk4Mjg4MDY5OTNjYTI2MTQxY2RhYWVmZTE2ZDJjMmJhMzQ2MjFjNWYwNDA4MjA4MTEzOWZjMDE5ZmIzNWFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.as1gRYqqQhAky1JmyH0DWAXTuJ2Orr9t8RV8xe6NMUc)
> 
> Mesmo com esse retorno de pagamento efetuado não houve atualização do Status do pedido.

Infelizmente não é uma correção que precise ser feita no módulo, é algo pontual do seu lado.

Confere com calma, faça os testes em ambiente de testes, se estiver em produção o modo manutenção deve estar bloqueando o recebimento das notificações para a atualização de status.

Atenciosamente,
Equipe PrestaBR

**Comment by kidultttttt** [comment]
Obrigado, vamos realizar algumas vendas fora do modo de manutenção e conferir.
