### ISSUE TITLE
Pagamento PIX não finaliza com campos de cartão vazio

### ISSUE THREAD

**Issue by rbastos6** [pagseguro/pagseguro-modulo-prestashop#153]
### O que aconteceu?

Quando tento finalizar uma compra com o PIX, o módulo reconhece que os campos do cartão de crédito estão vazio e não deixa seguir para finalização até preencher os campos.
Poderiam verificar por gentileza?
https://infopededu.com.br/loja/
Obrigado

### Versão da PrestaShop?

PS 1.6

### Versão do PHP?

PHP 5.6

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Boa Noite rbastos6,

Em nosso ambiente de testes e homologações não conseguimos reproduzir este problema na validação dos dados para as modalidades cartão/boleto/pix. A validação das informações são independentes para cada modalidade de pagamento na tela de checkout.

No link que você forneceu, https://infopededu.com.br/loja/, está com a PS 8.1 e somente o cartão habilitado.

Algumas sugestões:
- Na tela de checkout, verifica se existe algum conflito de JavaScript, confere no inspetor de elementos do navegador;
- Em muitos casos, o comportamento fora do esperado está comumente relacionado à problemas de permissões nos arquivos e diretórios na hospedagem. O ideal é 644 para arquivos e 755 para diretórios;
- Confere o gerenciador de logs do módulo, mais infos: https://github.com/pagseguro/pagseguro-modulo-prestashop?tab=readme-ov-file#5---debug--logs
- Se você atualizou o módulo do PagSeguroPro para o PagBank, segue o passo-a-passo de instalação, limpa o cache, e em seguida desativar o módulo PagSeguroPro.

Atenciosamente,
Equipe PrestaBR

**Comment by rbastos6** [comment]
Obrigado pelo retorno.
Eu desativei as outras funções pois precisavamos usar o sistema.
Mesmo ativando outras funções como PAGAMENTO POR CHEQUE o erro permanece.
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/29932561/f3b12331-1685-41b3-a556-13023d0a9099)
Quando marcamos a opção de EU CONCORDO COM OS TERMOS ele busca a validação desses campos.
Olhei os logs, procurei erro de JS e não identifiquei.
Deixei ativo aqui para você olhar.
obrigado

**Comment by rbastos6** [comment]
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/29932561/742aa510-7107-4b8d-97df-fe443e3ba70d)

**Comment by prestabr** [comment]
Bom Dia rbastos6,

Obrigado pelas informções!

Fizemos uma série de testes e conseguimos reproduzir problema dentro de um contexto pontual, quando a opção "termos de serviço" está ativa e o usuário decide validar os termos sem preencher os campos e em seguida repete o processo com outra modalidade de pagamento.

Vamos seguir com mais alguns testes e devemos lançar uma update dentro de 1 ou 2 dias, voltamos aqui para te avisar.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde rbastos6,

Tudo bem?

Só informando, já disponibilizamos aqui no Git a nova versão (v.1.5.2) com esta correção. P/ atualizar o módulo em sua loja basta seguir o passo-a-passo de instalação, na sequência limpa o cache da Plataforma (Parâmetros Avançados > Desempenho) e o do seu navegador se necessário.

Qualquer dúvida ou problema, por favor, fique à vontade para retornar o contato.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Oi rbastos6,

Não precisa refazer o credenciamento no App. Seguindo o passo-a-passo de instalação somente os arquivos do módulo serão atualizados, o credenciemento e configs salvas no módulo ficam intactas no banco de dados.

Atenciosamente,
Equipe PrestaBR
