### ISSUE TITLE
[Bug]: Módulo bloqueia botao de finalizar compra

### ISSUE THREAD

**Issue by rbastos6** [pagseguro/pagseguro-modulo-prestashop#154]
### O que aconteceu?

Oi, tudo bem?
Percebi que mesmo depois de preencher todos os dados do módulo, o botão de "Confirmar o Pedido"ficar travado.
![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/29932561/80c5eeb5-ac9c-4de7-9acc-234fff58124d)
Sendo que se eu apertar o "ENTER" ele finaliza a transação.

Isso acontece quando escolho CREDITO como primeira opção. Depois, se eu mudar para PIX ou Boleto e voltar para Crédito, ele habilita o botão.

Já olhei se está tendo algum conflito de CSS pelo meu lado mas náo consegui identificar, logo pensei que possa ter alguma validação dentro do módulo que faça esse controle.

Consegue ajudar?

### Versão da PrestaShop?

PS 8.0

### Versão do PHP?

PHP 5.6

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos

**Comment by rbastos6** [comment]
Você pode usar esse produto para teste:
https://infopededu.com.br/loja/index.php?id_product=22&rewrite=teste&controller=product

E aplicar esse cupom para baixar o valor: 5VHDHEF1

**Comment by prestabr** [comment]
Boa Tarde rbastos6,

Obrigado por retornar o contato e detalhar o problema!

Vamos realizar novos testes e fazer uma revisão geral do processo de validação com simulações diversas. Devemos lançar a update entre 2-3 dias, voltamos aqui para te avisar.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Noite rbastos6,

Tudo bem?

Só informando, a nova versão 1.5.3 já está disponível aqui no Git. P/ atualizar o módulo em sua loja basta seguir o passo-a-passo de instalação, na sequência limpa o cache da Plataforma (Parâmetros Avançados > Desempenho) e o do seu navegador se necessário.

Qualquer dúvida ou problema, por favor, fique à vontade para retornar o contato.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
