### ISSUE TITLE
[Feature]: Reserva no Cartão Crédito

### ISSUE THREAD

**Issue by DredsmanGT** [pagseguro/pagseguro-modulo-prestashop#155]
### Qual é o novo recurso que você gostaria de ver?

Eu trabalho com empresas que vendem alimentos pereciveis, e na maioria das vezes o peso dos produtos é váriavel, variando também o valor final da compra. Para poder trabalhar com o Pagbank neste caso, seria necessário efetuar uma reserva no cartão do cliente, como as locadoras de veículos, e depois que a mercadoria for pesada e o faturamento confirmado, ai confirmaria o valor definitivo da cobrança. A LOJA5 tem um modulo que já faz isso, mas necessita da homologação, e ainda exige recursos de php que alguns servidores não tem. Tenho quase 300 clientes que precisam desta solução de pré auth.

**Comment by prestabr** [comment]
Boa Tarde DredsmanGT,

Obrigado por entrar em contato detalhando a feature sugerida! Vamos levar em consideração para futuras updates.

Para algumas lojas com alto fluxo de vendas ou clientes com demandas específicas nós já desenvolvemos, testamos e homologamos esse modelo de integração com pré autorização, para posterior captura manual ou automática no cartão de crédito com operadora anti-fraudes.

Podemos disponibilizar a integração para atender o seu modelo de negócio, gostaria de agendar uma reunião para conversar sobre e alinhar os detalhes?

Passa pra gente o seu contato para o nosso email que agendamos um horário: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR
