### ISSUE TITLE
[Question]: Cobrança recorrente

### ISSUE THREAD

**Issue by ArthurSirius** [pagseguro/pagseguro-modulo-prestashop#156]
### Qual é a sua dúvida, como podemos ajudar?

Gostaria de saber se esse módulo tem suporte para criar pedidos de cobrança recorrente, uma assinatura em um serviço. Não encontrei nada nesse sentido, apenas cobranças únicas de produtos.

### Versão da PrestaShop

PS 8.0

**Comment by prestabr** [comment]
Boa Tarde ArthurSirius,

O módulo não tem suporte para pagamento recorrente, o foco é o checkout transparente. O pagamento recorrente utiliza uma estrutura diferente com outras regras e APIs do PagBank, por enquanto também não temos planos para desenvolver.

Qualquer dúvida fique à vontade para perguntar.

Atenciosamente,
Equipe PrestaBR
