### ISSUE TITLE
validação de cartão (config de permissões na hospedagem ou cartão de teste)

### ISSUE THREAD

**Issue by ricmyra** [pagseguro/pagseguro-modulo-prestashop#157]
### O que aconteceu?

Boa Tarde!

Estou testando o módulo Pagseguro para Prestashop 8.1.4 e logo após eu digitar o número do cartão aparece uma janela escrito VALIDANDO e essa janela nunca fecha, impossibilitando continuar com a finalização do pagamento. 

### Versão da PrestaShop?

PS 8.0

### Versão do PHP?

PHP 8.1

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos

**Comment by prestabr** [comment]
Boa Tarde ricmyra,

Obrigado por testar o módulo em sua loja!

Em nosso ambiente de testes e homologações não conseguimos reproduzir este problema na validação do cartão.

O comportamento fora do padrão esperado está comumente relacionado à problemas de permissões nos arquivos e diretórios na hospedagem, que pode variar dependendo das configurações do host.

O ideal, recomendado pela PrestaShop, é 644 para arquivos e 755 para diretórios. Essas permissões devem ser aplicadas de forma recursiva, pra tudo que estiver em sua /public_html/. 

Essa config é importante porque é requisito básico da Plataforma, quando não configurado podem surgir alguns problemas de funcionamento na loja ou módulos. https://docs.prestashop-project.org/v.8-documentation/getting-started/installing-prestashop#updating-chmod

Após conferir as permissões, por favor, acessa a tab de Logs do módulo para verificar a comunicação com a API. https://github.com/pagseguro/pagseguro-modulo-prestashop#5---debug--logs

Exemplo em funcionamento:


https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/556455b6-1153-4335-8a65-9aaf54721ca9

Se mesmo após setar as permissões não funcionar, por favor, acessa o checkout da loja e confere no inspetor de elementos do navegador se existe algum conflito de JavaScript e tira um print pra gente.

Aguardamos seu retorno.

Atenciosamente,
Equipe PrestaBR
