### ISSUE TITLE
Campo CPF travado (ajustes de layout [html/css], herdado do tema customizado da loja e alterações no módulo)

### ISSUE THREAD

**Issue by EduardoDalabona** [pagseguro/pagseguro-modulo-prestashop#158]
### O que aconteceu?

Olá.

Na opção PIX, quando o cliente vai efetuar a compra o campo onde deveria digitar o CNPJ/CPF está travado, no mesmo não é possível adicionar os dados e com isso a compra não pode ser finalizada.

![pix_travado](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/164194432/74a5b9ee-97c7-472d-92f5-22fe6272ace6)

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.4

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Boa Noite EduardoDalabona,

A tela original do módulo na versão 1.7.x da PS segue esse padrão:
![Screenshot at 2024-07-04 18-17-09](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/5f8c4a8a-3563-4db2-9261-f36797f27368)

No seu print parece que as informações estão se sobrepondo impedindo que o campo de CPF seja preenchido.

Você fez algum ajuste de layout ou está com o módulo em uma versão mais antiga?

A versão atual do módulo é a 1.6.1, por favor, verifique se a sua loja já utiliza esta versão e depois limpa o cache da PrestaShop e do seu navegador se necessário.

Aguardamos seu retorno!

Atenciosamente,
Equipe PrestaBR

**Comment by EduardoDalabona** [comment]
Olá, obrigado pelo retorno.

Nossa versão é a V1.6.1 conforme imagem abaixo:

![image](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/164194432/ae27f389-5230-44e0-8570-89f472b21bc7)

Mesmo limpando cache, não funciona.

**Comment by prestabr** [comment]
Olá EduardoDalabona,

Se o módulo já está na versão mais recente e o cache da PS está limpo, pode ser que o tema (layout) da sua loja esteja sobrepondo alguma configuração do layout da tela de pagamento.

Não é algo complicado de ajustar mas exige conhecimentos de html/css, aparentemente os campos (inputs) no seu print estão maiores que o normal (deve ter sido herdado do tema da loja).

Se você não tiver um técnico para te auxiliar neste ajuste nós podemos verificar para você. Por favor, encaminha p/ o nosso email sac@prestabr.com.br o endereço da sua loja com um usuário temporário para o admin + acesso ao ftp da hospedagem.

Atenciosamente,
Equipe PrestaBR

**Comment by EduardoDalabona** [comment]
Perfeito,

E-mail enviado!

Obrigado.

**Comment by prestabr** [comment]
Bom dia EduardoDalabona,

Só pra gente manter a issue atualizada...

Recebemos em nosso email sac@prestabr.com.br os dados de acesso ao Admin da Loja, mas ainda está pendende o do FTP da Hospedagem.

Quando você tiver o acesso ao FTP é só encaminhar pra gente, que no mesmo dia, ajustamos os detalhes de layout do cartão e pix no checkout da sua loja.

Atenciosamente,
Equipe PrestaBR

**Comment by EduardoDalabona** [comment]
Olá, bom dia

Segue:

SFTP: 134.122.36.22 / porta: 22 / u: prestabr / s: presta123BR


Atenciosamente,




Em seg., 8 de jul. de 2024 às 10:50, PrestaBR ***@***.***>
escreveu:

**Comment by prestabr** [comment]
Olá EduardoDalabona,

Obrigado pelas informações.

Por favor, evite postar por aqui qualquer informação sensível à sua loja, como acesso ao host/loja e/ou dados confidenciais de clientes. Neste canal o atendimento é público, por isso que pedimos para enviar p/ sac@prestabr.com.br.

Atenciosamente,
Equipe PrestaBR

**Comment by EduardoDalabona** [comment]
Obrigado, assim que finalizar me avisa por favor.

Atenciosamente,




Em seg., 8 de jul. de 2024 às 11:33, PrestaBR ***@***.***>
escreveu:

**Comment by prestabr** [comment]
Boa Tarde EduardoDalabona,

Fizemos alguns ajustes pontuais de CSS e deixamos em override:
/public_html/themes/bravoairsoft/modules/pagbank/css/pagbank.css

O cache da PS está limpo/desativado, mas quando puder é uma boa limpar o cache do CDN (CloudFlare) também.

Checkout PIX:
![Screenshot at 2024-07-08 12-43-20](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/6d2c4171-ee81-4d6c-a87d-88a530b7a84b)

Checkout Cartão:
![Screenshot at 2024-07-08 12-43-57](https://github.com/pagseguro/pagseguro-modulo-prestashop/assets/7054224/a6dd9ba8-c30c-4d82-bfb7-6205f1e37713)

Qualquer dúvida ou problema, fique à vontade para perguntar.

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR

**Comment by EduardoDalabona** [comment]
Boa tarde.

Muito obrigado!
