### ISSUE TITLE
[Question]: Posição do QRCode PIX no checkout.

### ISSUE THREAD

**Issue by kidultttttt** [pagseguro/pagseguro-modulo-prestashop#159]
### Qual é a sua dúvida, como podemos ajudar?

Olá!Tenho um cliente com um ecommercer que está perdendo vendas.
Os clientes alegam que não encontram o QRCode PIX para pagamento.
O problema é que no checkout, após gerar o o QRCode, ele aparece abaixo da lista de produtos.

![image](https://github.com/user-attachments/assets/4468bda5-7e61-4b44-a87d-bec260b64974)

É possível alterar a posição para que o QRCode aparece no topo da página?

### Versão da PrestaShop

PS 1.7

**Comment by prestabr** [comment]
Boa Noite kidultttttt,

Essa estrutura do layout na tela de confirmação do pedido é o padrão da Plataforma, exibe um resumo do pedido e logo em seguida as informações de pagamento.
Você pode alterar a posição das informações e qualquer outro detalhe que desejar, mas depende de ajuste no layout da loja e não no módulo de pagamento.

Para alterar, no tema padrão, é neste arquivo:
/public_html/themes/classic/templates/checkout/order-confirmation.tpl

Apenas uma sugestão, p/ deixar as informações de pagamento antes do resumo do pedido:

Localiza o {block name='hook_payment_return'}:
![Screenshot at 2024-07-30 20-50-20](https://github.com/user-attachments/assets/d185091e-bae0-42ea-84c2-e24666fd1012)

E move tudo p/ dentro do {block name='page_content_container'}, exemplo:
![Screenshot at 2024-07-30 20-50-42](https://github.com/user-attachments/assets/60ed9a6c-0943-4071-835c-23b796c8de00)

Desejamos Boas Vendas! :)

Atenciosamente,
Equipe PrestaBR
