### ISSUE TITLE
Problema PIX (ajustes de layout, msm issue #158)

### ISSUE THREAD

**Issue by EduardoDalabona** [pagseguro/pagseguro-modulo-prestashop#161]
### O que aconteceu?

Boa tarde.

A alguns meses atrás, vocês ja corrigiram esse problema, porém, o mesmo voltou a acontecer.

Ao tentar fazer o pagamento via PIX, o campo "CPF" fica travado, ou seja, o cliente não consegue colocar o seu CPF.

Na ultima vez, vocês mexeram no layout e corrigiram.

Não existe uma forma do modulo puxar o CPF do próprio cadastro do cliente?

Site: https://www.bravoarmas.com.br/

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.4

### Qual é a gravidade do problema?

Nenhum cliente consegue fazer pagamentos

**Comment by prestabr** [comment]
Boa Tarde EduardoDalabona,

Da última vez que falamos, o motivo era esse:
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/158#issuecomment-2209582156

E a solução foi essa:
https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/158#issuecomment-2214518118

Se o problema voltou significa que o arquivo em override que deixamos configurados no seu tema deve ter sido apagado ou sobreescrito.
É simples de resolver, ainda temos uma cópia do nosso lado, o acesso ao FTP da sua hospedagem ainda está liberado? Se sim, por favor, confirma pra gente que atualizamos pra você.

Sobre preencher o CPF automático, é possível, mas depende de ajustes mais complexos na loja/módulo e o ideal é que você tenha um técnico à disposição para realizar esses ajustes.
Mas não recomendamos o preenchimento automático porque o cliente pode precisar informar outro CPF na tela de pagamento, principalmente para cartão de crédito (evitando problemas com o antifraudes).

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá EduardoDalabona,

Verificamos aqui que ainda temos acesso ao ADM da sua loja, habilitamos o PIX e navegamos até o front, está tudo como deixamos da última vez, tudo ok:

![Screenshot at 2024-08-13 15-57-54](https://github.com/user-attachments/assets/0af38c43-9896-41f8-be64-1e9a78fbcc4f)

Você conseguiu subir novamente o arquivo em override?
Já conferiu se a loja tem algum problema de cache ou cdn?

Atenciosamente,
Equipe PrestaBR

**Comment by EduardoDalabona** [comment]
Olá, primeiramente obrigado novamente pelo pronto atendimento de vocês.

Infelizmente temos problemas com o desenvolvedor (neogest), existe uma alta demanda por conta dele, com isso demora para responder e em alguns pontos não é com a neogest.

Não entendo muito da parte de programação como a questão do cache e cdn, não mexi em nada desse tipo, única alteração que foi feita, foi na parte de alimentação de produtos, que faço com frequência, mas nada voltado ao modulo.

Hoje apenas desabilitei a opção de pix do pagseguro devido esse problema que havia e habilitei a opção de transferência/PIX manual para não deixar o site sem essa opção.

Caso tenha algo que possa fazer para não ocorrer mais esse problema, me informa por favor.

Obrigado!

**Comment by prestabr** [comment]
Olá EduardoDalabona,

Obrigado pelo feedback!
Com o módulo de pagamento e os ajustes de layout que fizemos p/ sua loja está tudo ok mesmo, nada mudou desde a última vez.
A sugestão é verificar se os mecanismos de cache da sua loja estão funcionando corretamente com o seu tema e se possível melhorar a performance do host, aqui pra gente a home do site levou uns 15s pra carregar.

Qualquer dúvida ou problema, conte com a gente.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Tarde EduardoDalabona,

Este problema é algo que, infelizmente, ocorre pontualmente em sua loja virtual.

Parece que existe algum problema de funcionamento na área de cache e/ou compilação do layout.

Os ajustes que lançamos são de CSS, é algo muito simples, e está funcionando em override, como já sinalizamos anteriormente: https://github.com/pagseguro/pagseguro-modulo-prestashop/issues/158#issuecomment-2214518118

Em sua loja, verificando a área "Parâmetros Avançados > Desempenho", o mecanismo de cache do Smarty está desabilitado e a opção "Recompilar Templates..." está ativa, é uma configuração incomum que geralmente é utilizada para desenvolvimento ou quando existe algum problema não resolvido.

Faz o teste e tenta limpar o cache da loja, ativa o cache do Smarty (que é padrão em qualquer tema/layout), testa também a opção "CCC (Combinação, Compressão e Cache)" que é excelente para melhorar a performance e ranqueamento da loja.

Uma opção p/ tentar contornar o problema é copiar o arquivo da override (pagbank.css) para o arquivo original do módulo em /public_html/pagbank/css/.

Outro ponto não menos importante são as permissões nos arquivos e diretórios da hospedagem, quando incorretas pode surgir um comportamento inesperado do sistema, por exemplo, a override está com a permissão 664 e o ideal/comum é 644 para arquivos:
![Screenshot at 2024-09-30 16-19-44](https://github.com/user-attachments/assets/12a38e32-5dac-480e-8b06-09b0f9861ecf)
A sugestão é manter os diretórios em 755 e os arquivos em 644.

Atenciosamente
Equipe PrestaBR
