### ISSUE TITLE
Não Funciona na Versão 1.7.7.5 Da PS (permissões na hospedagem e/ou cache travado)

### ISSUE THREAD

**Issue by Business2025** [pagseguro/pagseguro-modulo-prestashop#162]
### O que aconteceu?

Olá amigos, boa tarde! 
Dois pontos a considerar nesta última atualização do PagBank 1.7.0 - (Loja PS - versão 1.7.7.5 - PHP 7.2):
1 - Não permite instalação na versão da PS 1.7.7.5  (foi descompactado conforme orientação aqui no github) - vide imagem.
2 - Se possível, ativar o aviso de atualização no Gerenciados de Módulos - Atualizações.

![bug-nova-versao-pagbank-200824](https://github.com/user-attachments/assets/da083815-e3e9-4774-a748-13d91801a0f3)

### Versão da PrestaShop?

PS 1.7

### Versão do PHP?

PHP 7.2

### Qual é a gravidade do problema?

Não consegui instalar o modulo

**Comment by prestabr** [comment]
Boa Tarde Business2025,

Agradecemos o seu contato! :)

Do nosso lado não conseguimos reproduzir este problema em nosso ambiente de testes e homologações, não é o comportamento esperado do módulo.

Este problema pode ocorrer comumente na PS v.1.7 por 2 motivos:
- Permissões incorretas no servidor de hospedagem, com isso o sistema não consegue executar a upgrade, o ideal é 755 p/ diretórios e 644 p/ arquivos;
- Mecanismo de cache travado, é preciso limpar o cache no menu "Parâmetros Avançados > Desempenho";

Por favor, faça o teste, limpe o cache e confere as permissões no host. Na sequência você pode tentar repetir o processo ou apenas clicar em atualizar:
![Screenshot at 2024-08-20 14-41-45](https://github.com/user-attachments/assets/32e17ae2-0b52-44e1-b240-b6f7e3f26517)

Aguardamos o seu retorno!

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Boa Noite Business2025,

Esperamos que você tenha conseguido instalar o módulo em sua loja!

Caso ainda esteja com dificuldades e precise de ajuda, nós podemos instalar e configurar o módulo em sua loja, basta enviar os dados de acesso p/ o nosso email sac@prestabr.com.br.

P/ receber as notifcações sobre updates acesse o repositório (https://github.com/pagseguro/pagseguro-modulo-prestashop) e clique em "Notificações" p/ receber os alertas p/ o seu email cadastrado.

Qualquer dúvia ou problema, por favor, fique à vontade para perguntar. Conte com a gente..!

Atenciosamente,
Equipe PrestaBR
