### ISSUE TITLE
Desconto de 5% no pagamento Pix não aplicou no pedido. (configs de hospedagem)

### ISSUE THREAD

**Issue by WebGF** [pagseguro/pagseguro-modulo-prestashop#163]
### O que aconteceu?

Boa tarde,
Eu configurei hontem(07/10) desconto de 5% nos pagamentos via Pix na loja.
Teve uma compra que aplicou o desconto normalmente:
![image](https://github.com/user-attachments/assets/b800e5c3-d900-4e63-bf91-212830aa87e3)
E teve uma segunda que não aplicou:
![image](https://github.com/user-attachments/assets/cc93a998-e696-43f0-a447-62fca5ef901a)
Podem me dar um auxilio ? o porque aconteceu ou como resolver?
Desde ja agradeço pela atenção.
Att. Mauricio

### Versão da PrestaShop?

PS 1.6

### Versão do PHP?

PHP 7.0

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Boa Tarde WebGF,

No módulo, se o desconto estiver habilitado e configurado na modalidade de pagamento (cartão, boleto ou pix), ele iré a valer para todas as transações, sem nenhum critério para determinar se não será aplicado.

A sugestão é que verifique se a segunda transação é realmente via pix e se for confere se nesse meio tempo a configuração do módulo não foi alterada por engano.

Atenciosamente,
Equipe PrestaBR

**Comment by WebGF** [comment]
Boa tarde, obrigado pela velocidade no atendimento!

Eu conferi que o pagamento foi feito via PIX:
![image](https://github.com/user-attachments/assets/81e39b1f-c536-48f4-8cfc-0823f2a23db2)
E na conta do pagbank o pedido consta o desconto de 5%. 
O desconto ocorreu quando foi feito o pagamento ele só não apareceu no pedido no site. 
![image](https://github.com/user-attachments/assets/acab40fa-bebe-4676-acff-58348e11ded9)

**Comment by prestabr** [comment]
Oi WebGF,

Se o desconto consta no pedido no PagBank significa que ele foi gerado e processado corretamente pelo módulo de integração.

O que pode ter ocorrido é alguma dificuldade da loja em criar o voucher para vincular ao pedido, p/ exibir no histórico.

Esse tipo de problema, que é fora do comportamento padrão esperado, é comumente relacionado à questões de infraestrutura de hospedagem, podendo causar instabilidades e falhas de processamento, afetando a plataforma, integrações, etc.

A recomendação, para a Plataforma PrestaShop, é utilizar um host do tipo VPS. Verifica junto ao seu servidor a possibilidade de uma upgrade ou um melhor balanceamento da configuração do php/mysql. Isso vai garantir que a loja trabalhe com agilidade, sem travar processos ou apresentar lentidão e/ou travamento pontual.

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Bom Dia WebGF,

Qualquer dúvida ou problema, por favor, fique à vontade para perguntar ou abrir um novo ticket.

Atencionsamente,
Equipe PrestaBR
