### ISSUE TITLE
[Question]: Acesso à API

### ISSUE THREAD

**Issue by JoaoPortella** [pagseguro/pagseguro-modulo-prestashop#164]
### Qual é a sua dúvida, como podemos ajudar?

Boa noite!
Após realizar o cadastro no PagBank, eu ainda não consigo conectar. Entendi que o cadastro já está aprovado. 

Recebo esta mensagem de erro:

"Não foi possível realizar a integração.

Atualize a página e tente novamente. Caso o erro continue, entre em contato com PrestaShop-ecommerce-D30"

Como devo proceder, falta alguma etapa?
Vocês podem me passar algum e-mail para tentar resolver o que estiver pendente?
Grato!

### Versão da PrestaShop

PS 8.0

**Comment by prestabr** [comment]
Boa Noite JoaoPortella,

No módulo, em "Configurações do App", você está usando ambiente Produção ou Sandbox?

Se você estiver usando o ambiente Sandbox é possível que esteja ocorrendo alguma instabilidade pontual ou indiponibilidade temporária do serviço junto ao PagBank.

Você já tentou ou já está cadatrado em produção?

Atenciosamente,
Equipe PrestaBR

**Comment by JoaoPortella** [comment]
Olá, obrigado pela pronta resposta!

O erro me parece ser na fase de cadastro. Eu apenas instalei o módulo, atualizei meu cadastro no PagBan e depois recebi um e-mail dizendo que foi aprovado.

Quando entro no módulo, seleciono D14 ou D30, ele abre a página solicitando autorização para o App do PagBank, eu clico em Autorizar e então recebo a mensagem de erro... 
Só depois então que acredito poder escolher entre produção/sandbox.

**Comment by prestabr** [comment]
Bom Dia JoaoPortella,

Obrigado pelas informações.
A Autorização é a etapa final do cadastro e é do lado do PagBank, se ele não está autorizando pode ser algo pontual em sua conta (documentação ou algum outro problema).
Por favor, encaminha pro nosso email: sac@prestabr.com.br, um acesso temporário ao Admin da sua loja e o seu email de cadastro junto ao PagBank.
Vamos tentar realizar um cadastro a partir da sua loja, pra descartar qualquer problema técnico, e solicitar uma análise em sua conta no PagBank p/ identificar o motivo de não autorizar o cadastro.
Aguardamos seu retorno!

Atenciosamente,
Equipe PrestaBR

**Comment by JoaoPortella** [comment]
Não consigo conceder o acesso porque ainda estou em dev/local.

De qualquer forma, você pode solicitar a análise do cadastro e passar meu e-mail de contato?

Obrigado!

**Comment by prestabr** [comment]
Olá JoaoPortella,

Você está trabalhando em localhost, https://localhost/ ?
Se for o caso é o motivo de não passar no cadastro, tem que ser um endereço web https://www.minhaloja.com.br.
Encaminha pra gente o seu email que solicitamos a análise: sac@prestabr.com.br

Atenciosamente,
Equipe PrestaBR

**Comment by prestabr** [comment]
Olá JoaoPortella,

No caso o problema é a sua url localhost, não tem relação com o ambiente ser produção ou sandox. Depois que vc se cadastra e configura o ambiente já fica um alerta em destaque indicando o que está sendo usado.
Mas fica tranquilo, o importante é que conseguimos te ajudar a identificar problema!
Agradecemos o seu feedback, vamos considerar p/ próximas updates!
Qualquer dúvida ou problema, por favor, fique à vontade p/ perguntar.

Atenciosamente,
Equipe PrestaBR
