### ISSUE TITLE
Erro no pagamento PIX Modulo Pagseguro versão 1.72 (Chave Pix não configurada no App PagBank)

### ISSUE THREAD

**Issue by dredsman** [pagseguro/pagseguro-modulo-prestashop#165]
### O que aconteceu?

O modulo causa um erro 500 na no prestashop versão 8,10 php 8,10 , segue o log:

Warning: Undefined property: stdClass::$arrangements in /home1/sbalim42/public_html/loja/modules/pagbank/controllers/front/validation.php on line 118

Warning: Trying to access array offset on value of type null in /home1/sbalim42/public_html/loja/modules/pagbank/controllers/front/validation.php on line 118
[PrestaShopException]
A propriedade Order-&gt;payment está vazia.
at line 1103 in file classes/ObjectModel.php

1098.             }
1099. 
1100.             $message = $this->validateField($field, $this->$field);
1101.             if ($message !== true) {
1102.                 if ($die) {
1103.                     throw new PrestaShopException($message);
1104.                 }
1105. 
1106.                 return $error_return ? $message : false;
1107.             }
1108.         }
ObjectModelCore->validateFields - [line 318 - classes/ObjectModel.php]
ObjectModelCore->getFields - [line 306 - classes/order/Order.php]
OrderCore->getFields - [line 621 - classes/ObjectModel.php]
ObjectModelCore->add - [line 311 - classes/order/Order.php] - [2 Arguments]
OrderCore->add - [line 1074 - classes/PaymentModule.php]
PaymentModuleCore->createOrderFromCart - [line 354 - classes/PaymentModule.php] - [17 Arguments]
PaymentModuleCore->validateOrder - [line 139 - modules/pagbank/controllers/front/validation.php] - [9 Arguments]
PagBankValidationModuleFrontController->postProcess - [line 308 - classes/controller/Controller.php]
ControllerCore->run - [line 510 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 28 - index.php]

### Versão da PrestaShop?

PS 8.0

### Versão do PHP?

PHP 8.1

### Qual é a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by prestabr** [comment]
Bom Dia dredsman,

Em nosso ambiente de testes e homologações, utilizando a versão mais recente da PrestaShop (v.8.2.0), não conseguimos reproduzir o erro reportado, o módulo de integração funciona normalmente como o esperado.

Mas verificando os seus logs, parece que a loja não conseguiu criar o pedido porque você ainda não tem uma chave pix cadastrada em sua conta no App do Pagbank, para poder receber e processar pagamentos.

Por favor, acessa o App do PagBank p/ cadastrar a chave:
![Untitled](https://github.com/user-attachments/assets/b845743c-5537-4cac-beb5-7fda2f2d6fce)

Aguardamos seu retorno!

Atenciosamente,
Equipe PrestaBR
